'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Clock3, Crown, FlaskConical, Gauge, Map as MapIcon, Network, Pause, Play, Plus, Search, Sparkles, Target, Trash2, Trophy } from 'lucide-react';
import {
  engineSeason,
  eraHallOfFame,
  formatRunTime,
  insightBoardLabel,
  nextTargets,
  parseRunTime,
  projectedRank,
  projectedPlaceForTime,
  runnerCareerSnapshots,
  runnerArchetype,
  runnerRivalries,
  simulateRunnerScore,
  type InsightBoard,
  type InsightHistoryRow,
  type InsightPlayer,
  type InsightRun,
} from './insights';

type LabMode = 'simulator' | 'timeline' | 'map' | 'hall' | 'seasons';
type Scenario = { boardKey: string; time: string };

const labModes: Array<{ key: LabMode; label: string; icon: typeof FlaskConical }> = [
  { key: 'simulator', label: 'Runner Lab', icon: FlaskConical },
  { key: 'timeline', label: 'Career Playback', icon: Play },
  { key: 'map', label: 'Engine Map', icon: MapIcon },
  { key: 'hall', label: 'Era Hall', icon: Crown },
  { key: 'seasons', label: 'Seasons', icon: Trophy },
];

function fmt(value: number, decimals = 0) {
  return new Intl.NumberFormat('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals }).format(Number(value || 0));
}

function FlagChip({ url }: { url: string | null }) {
  // Flag URLs are generated by the site data pipeline and served locally.
  // eslint-disable-next-line @next/next/no-img-element
  return url ? <img className="flag" src={url} alt="" loading="lazy" decoding="async" /> : <span className="flag flag-placeholder" />;
}

function RunnerSearch({ players, value, onChange, label = 'Runner' }: { players: InsightPlayer[]; value: string; onChange: (runner: string) => void; label?: string }) {
  const [query, setQuery] = useState(value);
  const [open, setOpen] = useState(false);
  const matches = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase();
    return players.filter((player) => !needle || player.Runner.toLocaleLowerCase().includes(needle)).slice(0, 12);
  }, [players, query]);
  const shownValue = open ? query : value;
  return <label className="lab-runner-field"><span>{label}</span><div className="lab-runner-input"><Search size={16} /><input value={shownValue} onFocus={() => { setOpen(true); setQuery(''); }} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} onBlur={() => setTimeout(() => setOpen(false), 120)} placeholder="Search runners" />{open && <div className="lab-runner-results">{matches.map((player) => <button type="button" key={player.Runner} onMouseDown={(event) => { event.preventDefault(); onChange(player.Runner); setQuery(player.Runner); setOpen(false); }}><FlagChip url={player['Flag URL']} /><span><strong>{player.Runner}</strong><small>{player.Country || 'Unlisted country'}</small></span><em>#{player.Rank}</em></button>)}{!matches.length && <p>No runners found.</p>}</div>}</div></label>;
}

export default function InsightsLab({ players, runs, boards, yearly, gameNames, openProfile }: { players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; yearly: InsightHistoryRow[]; gameNames: Record<string, string>; openProfile: (runner: string) => void }) {
  const [mode, setMode] = useState<LabMode>('simulator');
  const [runner, setRunner] = useState(players[0]?.Runner || '');
  const selected = players.find((player) => player.Runner === runner) || players[0] || null;

  return <section className="view-section insights-view"><div className="page-heading lab-heading"><div><p className="eyebrow">Explore the engine differently</p><h2>Insights Lab</h2></div><Sparkles size={28} /></div><nav className="lab-tabs" aria-label="Insights Lab tools">{labModes.map(({ key, label, icon: Icon }) => <button key={key} className={mode === key ? 'active' : ''} onClick={() => setMode(key)}><Icon size={16} />{label}</button>)}</nav>{mode === 'simulator' && selected && <RunnerLab player={selected} players={players} runs={runs} boards={boards} runner={runner} setRunner={setRunner} gameNames={gameNames} openProfile={openProfile} />}{mode === 'timeline' && selected && <CareerPlayback player={selected} players={players} runs={runs} runner={runner} setRunner={setRunner} gameNames={gameNames} openProfile={openProfile} />}{mode === 'map' && selected && <EngineMap player={selected} players={players} runs={runs} boards={boards} runner={runner} setRunner={setRunner} gameNames={gameNames} />}{mode === 'hall' && <EraHall rows={yearly} openProfile={openProfile} />}{mode === 'seasons' && <EngineSeasons players={players} runs={runs} openProfile={openProfile} />}</section>;
}

function RunnerLab({ player, players, runs, boards, runner, setRunner, gameNames, openProfile }: { player: InsightPlayer; players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; runner: string; setRunner: (runner: string) => void; gameNames: Record<string, string>; openProfile: (runner: string) => void }) {
  const targets = useMemo(() => nextTargets(player, runs, boards, 8), [boards, player, runs]);
  const rivals = useMemo(() => runnerRivalries(player, runs, players, 5), [player, players, runs]);
  const archetype = useMemo(() => runnerArchetype(player), [player]);
  const defaultScenario = useMemo(() => targets[0] ? [{ boardKey: targets[0].board.boardKey, time: targets[0].goalTime }] : [], [targets]);
  const [scenarioState, setScenarioState] = useState<{ runner: string; rows: Scenario[] }>({ runner: player.Runner, rows: defaultScenario });
  const scenarios = scenarioState.runner === player.Runner ? scenarioState.rows : defaultScenario;
  const timedScenarios = useMemo(() => scenarios.map((scenario) => ({ boardKey: scenario.boardKey, seconds: parseRunTime(scenario.time) })), [scenarios]);
  const projection = useMemo(() => simulateRunnerScore(player, runs, boards, timedScenarios), [boards, player, runs, timedScenarios]);
  const newRank = projectedRank(players, player.Runner, projection.score);

  function updateScenarios(updater: (rows: Scenario[]) => Scenario[]) {
    setScenarioState((current) => ({ runner: player.Runner, rows: updater(current.runner === player.Runner ? current.rows : defaultScenario) }));
  }

  function suggestedTime(boardKey: string) {
    const target = targets.find((item) => item.board.boardKey === boardKey);
    if (target) return target.goalTime;
    const existing = runs.find((run) => run.runner === player.Runner && run.boardKey === boardKey);
    if (existing?.seconds) return formatRunTime(Math.max(0.001, existing.seconds - 0.001));
    const boardTimes = runs.filter((run) => run.boardKey === boardKey && run.seconds > 0).map((run) => run.seconds).sort((a, b) => a - b);
    return boardTimes.length ? formatRunTime(boardTimes[Math.floor(boardTimes.length / 2)]) : '0:00.000';
  }

  return <div className="lab-stack">
    <section className="lab-band runner-lab-header"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Run the numbers for" /><button className="profile-jump" onClick={() => openProfile(player.Runner)}>Open full profile</button></section>
    <div className="lab-split">
      <section className="lab-panel simulator-panel">
        <div className="lab-panel-title"><div><span>What-if simulator</span><h3>Enter the times you want to achieve</h3></div><FlaskConical size={22} /></div>
        <p className="lab-explainer">Times are converted into placements from the current included leaderboard, then scored with the same performance, volume and variety formula.</p>
        <div className="simulation-score"><div><span>Current</span><strong>#{player.Rank}</strong><small>{fmt(player['Total Score'], 2)} points</small></div><b>to</b><div className={newRank < player.Rank ? 'improved' : ''}><span>Projected</span><strong>#{newRank}</strong><small>{fmt(projection.score, 2)} points</small></div><em>{projection.delta >= 0 ? '+' : ''}{fmt(projection.delta, 2)}</em></div>
        <div className="scenario-list">{scenarios.map((scenario, index) => {
          const seconds = parseRunTime(scenario.time);
          const place = projectedPlaceForTime(player.Runner, scenario.boardKey, seconds, runs);
          return <div className="scenario-row" key={`${player.Runner}-${index}`}><label><span>Board</span><select value={scenario.boardKey} onChange={(event) => updateScenarios((rows) => rows.map((row, rowIndex) => rowIndex === index ? { boardKey: event.target.value, time: suggestedTime(event.target.value) } : row))}>{boards.map((board) => <option value={board.boardKey} key={board.boardKey}>{gameNames[board.gameAbbr] || board.gameAbbr} - {insightBoardLabel(board)}</option>)}</select></label><label className="time-field"><span>Target time</span><input type="text" inputMode="decimal" value={scenario.time} placeholder="4:55.000" onChange={(event) => updateScenarios((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, time: event.target.value } : row))} /><small>{place ? `Estimated place: #${place}` : 'Enter m:ss.mmm'}</small></label><button className="icon-button" title="Remove scenario" aria-label="Remove scenario" onClick={() => updateScenarios((rows) => rows.filter((_, rowIndex) => rowIndex !== index))}><Trash2 size={15} /></button></div>;
        })}</div>
        <button className="add-scenario" disabled={scenarios.length >= 5 || !boards.length} onClick={() => updateScenarios((rows) => { const next = targets.find((target) => !rows.some((row) => row.boardKey === target.board.boardKey)); const boardKey = next?.board.boardKey || boards.find((board) => !rows.some((row) => row.boardKey === board.boardKey))?.boardKey || boards[0]?.boardKey || ''; return [...rows, { boardKey, time: next?.goalTime || suggestedTime(boardKey) }]; })}><Plus size={15} /> Add target time</button>
        <div className="projection-breakdown"><span>Performance <strong>{projection.performanceDelta >= 0 ? '+' : ''}{fmt(projection.performanceDelta, 2)}</strong></span><span>Volume <strong>+{fmt(projection.volumeDelta, 2)}</strong></span><span>Variety <strong>{projection.varietyDelta >= 0 ? '+' : ''}{fmt(projection.varietyDelta, 2)}</strong></span></div>
      </section>
      <aside className="lab-panel archetype-panel"><div className="archetype-mark"><Sparkles size={20} /><span>Runner archetype</span></div><h3>{archetype.name}</h3><p>{archetype.detail}</p><div className="trait-list">{archetype.traits.map((trait) => <span key={trait}>{trait}</span>)}</div><dl><div><dt>Current rank</dt><dd>#{player.Rank}</dd></div><div><dt>Boards</dt><dd>{player['Unique Boards']}</dd></div><div><dt>WRs</dt><dd>{player.WRs}</dd></div></dl></aside>
    </div>
    <div className="lab-split lower">
      <section className="lab-panel"><div className="lab-panel-title"><div><span>Rivalry network</span><h3>Closest competitive neighbors</h3></div><Network size={21} /></div><p className="lab-explainer">Rivals are runners who share many boards with you, especially where the placements are close.</p><div className="rivalry-network"><button className="rival-center" onClick={() => openProfile(player.Runner)}><FlagChip url={player['Flag URL']} /><strong>{player.Runner}</strong><small>#{player.Rank}</small></button>{rivals.map((rival) => <button className="rival-node" onClick={() => openProfile(rival.runner)} key={rival.runner}><FlagChip url={rival.flagUrl} /><span><strong>{rival.runner}</strong><small>{rival.shared} shared boards · {rival.close} within 3 places</small></span><span className="rival-record"><b>You lead {rival.wins}</b><small>You trail {rival.losses}</small></span></button>)}</div></section>
      <section className="lab-panel"><div className="lab-panel-title"><div><span>Concrete goals</span><h3>Highest estimated score gains</h3></div><Target size={21} /></div><p className="lab-explainer">Each goal names a real time to beat. Estimated gain includes performance and, for a new board, volume and game variety.</p><div className="target-list">{targets.slice(0, 6).map((target) => <button key={target.board.boardKey} onClick={() => updateScenarios(() => [{ boardKey: target.board.boardKey, time: target.goalTime }])}><Clock3 size={15} /><span><strong>{gameNames[target.board.gameAbbr] || target.board.gameAbbr} - {insightBoardLabel(target.board)}</strong><small>{target.goalLabel}: beat {target.goalTime} for about #{target.proposedPlace}</small></span><em>+{fmt(target.estimatedGain, 2)}</em></button>)}</div></section>
    </div>
  </div>;
}

function CareerPlayback({ player, players, runs, runner, setRunner, gameNames, openProfile }: { player: InsightPlayer; players: InsightPlayer[]; runs: InsightRun[]; runner: string; setRunner: (runner: string) => void; gameNames: Record<string, string>; openProfile: (runner: string) => void }) {
  const snapshots = useMemo(() => runnerCareerSnapshots(player, runs), [player, runs]);
  const [playback, setPlayback] = useState({ runner: player.Runner, index: Math.max(0, snapshots.length - 1), playing: false });
  const index = playback.runner === player.Runner ? Math.min(playback.index, Math.max(0, snapshots.length - 1)) : Math.max(0, snapshots.length - 1);
  const playing = playback.runner === player.Runner && playback.playing;
  useEffect(() => {
    if (!playing || !snapshots.length) return;
    const timer = window.setInterval(() => setPlayback((current) => { const currentIndex = current.runner === player.Runner ? current.index : 0; if (currentIndex >= snapshots.length - 1) return { runner: player.Runner, index: currentIndex, playing: false }; return { runner: player.Runner, index: currentIndex + 1, playing: true }; }), 900);
    return () => window.clearInterval(timer);
  }, [player.Runner, playing, snapshots.length]);
  const snapshot = snapshots[index];
  const maxScore = Math.max(1, ...snapshots.map((item) => item.score));
  const label = snapshot ? new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${snapshot.period}-01T00:00:00Z`)) : 'No dated runs';
  return <div className="lab-stack">
    <section className="lab-band runner-lab-header"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Play back the career of" /><button className="profile-jump" onClick={() => openProfile(player.Runner)}>Open full profile</button></section>
    {snapshot ? <>
      <section className="lab-band playback-controls"><button className="play-button" onClick={() => setPlayback({ runner: player.Runner, index: index >= snapshots.length - 1 ? 0 : index, playing: !playing })}>{playing ? <Pause size={17} /> : <Play size={17} />}{playing ? 'Pause' : 'Play career'}</button><div><strong>{label}</strong><span>{snapshot.newRuns.length} portfolio addition{snapshot.newRuns.length === 1 ? '' : 's'} this month</span></div><input aria-label="Career period" type="range" min="0" max={Math.max(0, snapshots.length - 1)} value={index} onChange={(event) => setPlayback({ runner: player.Runner, index: Number(event.target.value), playing: false })} /></section>
      <section className="lab-panel career-panel"><div className="lab-panel-title"><div><span>Career playback</span><h3>{player.Runner}&apos;s current portfolio, built over time</h3></div><CalendarDays size={21} /></div><p className="lab-explainer">This stages the runner&apos;s current non-obsolete runs by the date each run was performed. Scores use today&apos;s board sizes and placements, so it shows how the current resume was assembled rather than a frozen historical leaderboard.</p>
        <div className="career-hero"><div><span>Portfolio score by {label}</span><strong>{fmt(snapshot.score, 2)}</strong><em>+{fmt(snapshot.scoreGain, 2)} added this period</em></div><div className="career-stat-grid"><span><b>{snapshot.runs}</b>runs</span><span><b>{snapshot.boards}</b>boards</span><span><b>{snapshot.games}</b>games</span><span><b>{snapshot.wrs}</b>current WRs</span></div></div>
        <div className="career-trail" aria-label="Career score timeline">{snapshots.map((item, itemIndex) => <button key={item.period} className={itemIndex === index ? 'active' : ''} title={`${item.period}: ${fmt(item.score, 2)} points`} onClick={() => setPlayback({ runner: player.Runner, index: itemIndex, playing: false })}><i style={{ height: `${Math.max(8, item.score / maxScore * 100)}%` }} /><span>{item.period.slice(2)}</span></button>)}</div>
        <div className="career-events"><div className="career-events-head"><span>Added in {label}</span><strong>{snapshot.newRuns.length} run{snapshot.newRuns.length === 1 ? '' : 's'} · +{fmt(snapshot.scoreGain, 2)} points</strong></div>{snapshot.newRuns.slice(0, 8).map((run) => <article key={`${run.boardKey}-${run.runner}`}><span>{gameNames[run.gameAbbr] || run.gameAbbr}</span><strong>{insightBoardLabel({ category: run.category, level: run.level, subcategory: run.subcategory })}</strong><em>{run.time || formatRunTime(run.seconds)}</em><small>#{run.place} · {fmt(run.performancePoints, 2)} performance</small></article>)}{snapshot.newRuns.length > 8 && <p>Plus {snapshot.newRuns.length - 8} more additions in this period.</p>}</div>
      </section>
    </> : <section className="lab-panel career-empty"><CalendarDays size={28} /><h3>No performed dates are available for {player.Runner}</h3><p>Career playback needs a run date from Speedrun.com.</p></section>}
  </div>;
}

function EngineMap({ player, players, runs, boards, runner, setRunner, gameNames }: { player: InsightPlayer; players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; runner: string; setRunner: (runner: string) => void; gameNames: Record<string, string> }) {
  const games = useMemo(() => Array.from(new Set(boards.map((board) => board.gameAbbr))), [boards]);
  const [game, setGame] = useState(games[0] || '');
  const [selectedKey, setSelectedKey] = useState('');
  const own = useMemo(() => new Map(runs.filter((run) => run.runner === player.Runner).map((run) => [run.boardKey, run])), [player.Runner, runs]);
  const shownBoards = boards.filter((board) => board.gameAbbr === (games.includes(game) ? game : games[0]));
  const selectedBoard = shownBoards.find((board) => board.boardKey === selectedKey) || shownBoards[0];
  const selectedRun = selectedBoard ? own.get(selectedBoard.boardKey) : null;
  const conquered = shownBoards.filter((board) => own.has(board.boardKey)).length;
  const medals = shownBoards.filter((board) => Number(own.get(board.boardKey)?.place || 999) <= 3).length;
  const records = shownBoards.filter((board) => Number(own.get(board.boardKey)?.place || 999) === 1).length;
  return <div className="lab-stack"><section className="lab-band map-toolbar"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Map for" /><div className="map-game-tabs">{games.map((item) => <button className={(games.includes(game) ? game : games[0]) === item ? 'active' : ''} key={item} onClick={() => { setGame(item); setSelectedKey(''); }}>{gameNames[item] || item}</button>)}</div></section><section className="lab-panel engine-map-panel"><div className="map-summary"><div><span>Conquered</span><strong>{conquered}/{shownBoards.length}</strong></div><div><span>Medals</span><strong>{medals}</strong></div><div><span>World records</span><strong>{records}</strong></div></div><div className="engine-map-grid">{shownBoards.map((board, index) => { const run = own.get(board.boardKey); const state = !run ? 'missing' : run.place === 1 ? 'wr' : run.place <= 3 ? 'medal' : 'ranked'; return <button className={`map-node ${state} ${selectedBoard?.boardKey === board.boardKey ? 'selected' : ''}`} key={board.boardKey} onClick={() => setSelectedKey(board.boardKey)}><span>{index + 1}</span><strong>{board.category}</strong><small>{[board.level, board.subcategory].filter(Boolean).join(' - ') || board.game}</small><em>{run ? `#${run.place}` : '?'}</em></button>; })}</div>{selectedBoard && <div className="map-detail"><span>{gameNames[selectedBoard.gameAbbr] || selectedBoard.gameAbbr}</span><strong>{insightBoardLabel(selectedBoard)}</strong><p>{selectedRun ? `${player.Runner} is #${selectedRun.place} of ${selectedRun.boardSize} with ${fmt(selectedRun.performancePoints, 2)} performance points.` : `${player.Runner} has not submitted to this ${selectedBoard.runCount}-runner board.`}</p></div>}</section></div>;
}

function EraHall({ rows, openProfile }: { rows: InsightHistoryRow[]; openProfile: (runner: string) => void }) {
  const careers = useMemo(() => eraHallOfFame(rows).slice(0, 40), [rows]);
  return <section className="lab-panel hall-panel"><div className="lab-panel-title"><div><span>Era dominance</span><h3>Who was strongest relative to their own time?</h3></div><Crown size={22} /></div><div className="era-key"><article><span>Peak</span><strong>Best single year</strong><small>100 means that year&apos;s performance leader.</small></article><article><span>Prime</span><strong>Best three-year form</strong><small>A 50/30/20 weighted average of the strongest seasons.</small></article><article><span>Rating</span><strong>Career score out of 100</strong><small>Prime form adjusted for longevity, reaching full weight at five seasons.</small></article></div><div className="hall-table"><div className="hall-head"><span>Rank</span><span>Runner</span><span>Best season</span><span>Peak / prime</span><span>Rating</span></div>{careers.map((career, index) => <button key={career.runner} onClick={() => openProfile(career.runner)}><span>{index + 1}</span><strong>{career.runner}<small>{career.seasons} scored season{career.seasons === 1 ? '' : 's'}</small></strong><span>{career.bestYear}<small>finished #{career.bestRank}</small></span><em>{fmt(career.bestIndex, 1)}<small>{fmt(career.primeIndex, 1)} prime</small></em><b>{fmt(career.rating, 1)}</b></button>)}</div></section>;
}

function EngineSeasons({ players, runs, openProfile }: { players: InsightPlayer[]; runs: InsightRun[]; openProfile: (runner: string) => void }) {
  const currentYear = new Date().getUTCFullYear();
  const years = useMemo(() => Array.from({ length: Math.max(1, currentYear - 2015 + 1) }, (_, index) => currentYear - index), [currentYear]);
  const [year, setYear] = useState(currentYear);
  const activeYear = years.includes(year) ? year : currentYear;
  const standings = useMemo(() => engineSeason(runs, players, activeYear).slice(0, 40), [activeYear, players, runs]);
  const rounds = useMemo(() => new Set(runs.filter((run) => String(run.runDate || '').startsWith(`${activeYear}-`)).map((run) => String(run.runDate).slice(0, 7))).size, [activeYear, runs]);
  const champion = standings[0];
  const mostWins = [...standings].sort((a, b) => b.wins - a.wins || b.points - a.points)[0];
  const ironRunner = [...standings].sort((a, b) => b.appearances - a.appearances || b.points - a.points)[0];
  return <div className="lab-stack"><section className="lab-band season-toolbar"><div><span>Engine season</span><strong>{activeYear}</strong><small>{rounds} monthly round{rounds === 1 ? '' : 's'} recorded</small></div><select value={activeYear} onChange={(event) => setYear(Number(event.target.value))}>{years.map((item) => <option value={item} key={item}>{item}</option>)}</select></section><div className="season-awards"><article><Trophy size={19} /><span>Championship leader</span><strong>{champion?.runner || '-'}</strong><small>{champion?.points || 0} points</small></article><article><Crown size={19} /><span>Most monthly wins</span><strong>{mostWins?.runner || '-'}</strong><small>{mostWins?.wins || 0} win{mostWins?.wins === 1 ? '' : 's'}</small></article><article><Gauge size={19} /><span>Most active months</span><strong>{ironRunner?.runner || '-'}</strong><small>{ironRunner?.appearances || 0} appearance{ironRunner?.appearances === 1 ? '' : 's'}</small></article></div><section className="lab-panel season-panel"><div className="lab-panel-title"><div><span>Every season from 2015</span><h3>{activeYear} monthly championship</h3></div><Trophy size={22} /></div><p className="lab-explainer">Current non-obsolete runs are grouped by their performed date. Each month is scored independently, then awards 25-18-15-12-10-8-6-4-2-1 championship points to its top ten.</p>{standings.length ? <div className="season-table">{standings.map((standing, index) => <button key={standing.runner} onClick={() => openProfile(standing.runner)}><span>{index + 1}</span><strong>{standing.runner}<small>{standing.appearances} active month{standing.appearances === 1 ? '' : 's'} · {standing.podiums} podium{standing.podiums === 1 ? '' : 's'}</small></strong><em>{standing.wins} win{standing.wins === 1 ? '' : 's'}</em><b>{standing.points}</b></button>)}</div> : <div className="season-empty"><CalendarDays size={24} /><strong>No dated runs in this season</strong><span>Try another year or include more games and categories.</span></div>}</section></div>;
}
