'use client';

import { useEffect, useMemo, useState } from 'react';
import { Crown, FlaskConical, Gauge, Map as MapIcon, Network, Pause, Play, Plus, Search, Sparkles, Target, Trash2, Trophy } from 'lucide-react';
import {
  engineSeason,
  eraHallOfFame,
  insightBoardLabel,
  nextTargets,
  projectedRank,
  runnerArchetype,
  runnerRivalries,
  simulateRunnerScore,
  type InsightBoard,
  type InsightHistoryRow,
  type InsightPlayer,
  type InsightRun,
} from './insights';

type LabMode = 'simulator' | 'timeline' | 'map' | 'hall' | 'seasons';
type Scenario = { boardKey: string; place: number };

const labModes: Array<{ key: LabMode; label: string; icon: typeof FlaskConical }> = [
  { key: 'simulator', label: 'Runner Lab', icon: FlaskConical },
  { key: 'timeline', label: 'Career Playback', icon: Play },
  { key: 'map', label: 'Engine Map', icon: MapIcon },
  { key: 'hall', label: 'Era Hall', icon: Crown },
  { key: 'seasons', label: 'Seasons', icon: Trophy },
];

function fmt(value: number, decimals = 0) {
  return new Intl.NumberFormat('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals }).format(Number(value || 0));
}

function FlagChip({ url }: { url: string | null }) {
  // Flag URLs are generated by the site data pipeline and served locally.
  // eslint-disable-next-line @next/next/no-img-element
  return url ? <img className="flag" src={url} alt="" loading="lazy" decoding="async" /> : <span className="flag flag-placeholder" />;
}

function RunnerSearch({ players, value, onChange, label = 'Runner' }: { players: InsightPlayer[]; value: string; onChange: (runner: string) => void; label?: string }) {
  const [query, setQuery] = useState(value);
  const [open, setOpen] = useState(false);
  const matches = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase();
    return players.filter((player) => !needle || player.Runner.toLocaleLowerCase().includes(needle)).slice(0, 12);
  }, [players, query]);
  const shownValue = open ? query : value;
  return <label className="lab-runner-field"><span>{label}</span><div className="lab-runner-input"><Search size={16} /><input value={shownValue} onFocus={() => { setOpen(true); setQuery(''); }} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} onBlur={() => setTimeout(() => setOpen(false), 120)} placeholder="Search runners" />{open && <div className="lab-runner-results">{matches.map((player) => <button type="button" key={player.Runner} onMouseDown={(event) => { event.preventDefault(); onChange(player.Runner); setQuery(player.Runner); setOpen(false); }}><FlagChip url={player['Flag URL']} /><span><strong>{player.Runner}</strong><small>{player.Country || 'Unlisted country'}</small></span><em>#{player.Rank}</em></button>)}{!matches.length && <p>No runners found.</p>}</div>}</div></label>;
}

export default function InsightsLab({ players, runs, boards, monthly, yearly, gameNames, openProfile }: { players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; monthly: InsightHistoryRow[]; yearly: InsightHistoryRow[]; gameNames: Record<string, string>; openProfile: (runner: string) => void }) {
  const [mode, setMode] = useState<LabMode>('simulator');
  const [runner, setRunner] = useState(players[0]?.Runner || '');
  const selected = players.find((player) => player.Runner === runner) || players[0] || null;

  return <section className="view-section insights-view"><div className="page-heading lab-heading"><div><p className="eyebrow">Explore the engine differently</p><h2>Insights Lab</h2></div><Sparkles size={28} /></div><nav className="lab-tabs" aria-label="Insights Lab tools">{labModes.map(({ key, label, icon: Icon }) => <button key={key} className={mode === key ? 'active' : ''} onClick={() => setMode(key)}><Icon size={16} />{label}</button>)}</nav>{mode === 'simulator' && selected && <RunnerLab player={selected} players={players} runs={runs} boards={boards} runner={runner} setRunner={setRunner} gameNames={gameNames} openProfile={openProfile} />}{mode === 'timeline' && <CareerPlayback rows={monthly} openProfile={openProfile} />}{mode === 'map' && selected && <EngineMap player={selected} players={players} runs={runs} boards={boards} runner={runner} setRunner={setRunner} gameNames={gameNames} />}{mode === 'hall' && <EraHall rows={yearly} openProfile={openProfile} />}{mode === 'seasons' && <EngineSeasons rows={monthly} openProfile={openProfile} />}</section>;
}

function RunnerLab({ player, players, runs, boards, runner, setRunner, gameNames, openProfile }: { player: InsightPlayer; players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; runner: string; setRunner: (runner: string) => void; gameNames: Record<string, string>; openProfile: (runner: string) => void }) {
  const targets = useMemo(() => nextTargets(player, runs, boards, 8), [boards, player, runs]);
  const rivals = useMemo(() => runnerRivalries(player, runs, players, 5), [player, players, runs]);
  const archetype = useMemo(() => runnerArchetype(player), [player]);
  const defaultScenario = targets[0] ? [{ boardKey: targets[0].board.boardKey, place: targets[0].proposedPlace }] : [];
  const [scenarioState, setScenarioState] = useState<{ runner: string; rows: Scenario[] }>({ runner: player.Runner, rows: defaultScenario });
  const scenarios = scenarioState.runner === player.Runner ? scenarioState.rows : defaultScenario;
  const projection = useMemo(() => simulateRunnerScore(player, runs, boards, scenarios), [boards, player, runs, scenarios]);
  const newRank = projectedRank(players, player.Runner, projection.score);

  function updateScenarios(updater: (rows: Scenario[]) => Scenario[]) {
    setScenarioState((current) => ({ runner: player.Runner, rows: updater(current.runner === player.Runner ? current.rows : defaultScenario) }));
  }

  return <div className="lab-stack"><section className="lab-band runner-lab-header"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Run the numbers for" /><button className="profile-jump" onClick={() => openProfile(player.Runner)}>Open full profile</button></section><div className="lab-split"><section className="lab-panel simulator-panel"><div className="lab-panel-title"><div><span>What-if simulator</span><h3>Build a hypothetical submission set</h3></div><FlaskConical size={22} /></div><div className="simulation-score"><div><span>Current</span><strong>#{player.Rank}</strong><small>{fmt(player['Total Score'], 2)} points</small></div><b>to</b><div className={newRank < player.Rank ? 'improved' : ''}><span>Projected</span><strong>#{newRank}</strong><small>{fmt(projection.score, 2)} points</small></div><em>{projection.delta >= 0 ? '+' : ''}{fmt(projection.delta, 2)}</em></div><div className="scenario-list">{scenarios.map((scenario, index) => <div className="scenario-row" key={`${player.Runner}-${index}`}><label><span>Board</span><select value={scenario.boardKey} onChange={(event) => updateScenarios((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, boardKey: event.target.value } : row))}>{boards.map((board) => <option value={board.boardKey} key={board.boardKey}>{gameNames[board.gameAbbr] || board.gameAbbr} - {insightBoardLabel(board)}</option>)}</select></label><label className="place-field"><span>Projected place</span><input type="number" min="1" value={scenario.place} onChange={(event) => updateScenarios((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, place: Math.max(1, Number(event.target.value || 1)) } : row))} /></label><button className="icon-button" title="Remove scenario" aria-label="Remove scenario" onClick={() => updateScenarios((rows) => rows.filter((_, rowIndex) => rowIndex !== index))}><Trash2 size={15} /></button></div>)}</div><button className="add-scenario" disabled={scenarios.length >= 5 || !boards.length} onClick={() => updateScenarios((rows) => [...rows, { boardKey: targets.find((target) => !rows.some((row) => row.boardKey === target.board.boardKey))?.board.boardKey || boards[0]?.boardKey || '', place: targets[0]?.proposedPlace || 1 }])}><Plus size={15} /> Add hypothetical run</button><div className="projection-breakdown"><span>Performance <strong>{projection.performanceDelta >= 0 ? '+' : ''}{fmt(projection.performanceDelta, 2)}</strong></span><span>Volume <strong>+{fmt(projection.volumeDelta, 2)}</strong></span><span>Variety <strong>{projection.varietyDelta >= 0 ? '+' : ''}{fmt(projection.varietyDelta, 2)}</strong></span></div></section><aside className="lab-panel archetype-panel"><div className="archetype-mark"><Sparkles size={20} /><span>Runner archetype</span></div><h3>{archetype.name}</h3><p>{archetype.detail}</p><div className="trait-list">{archetype.traits.map((trait) => <span key={trait}>{trait}</span>)}</div><dl><div><dt>Current rank</dt><dd>#{player.Rank}</dd></div><div><dt>Boards</dt><dd>{player['Unique Boards']}</dd></div><div><dt>WRs</dt><dd>{player.WRs}</dd></div></dl></aside></div><div className="lab-split lower"><section className="lab-panel"><div className="lab-panel-title"><div><span>Rivalry network</span><h3>Closest competitive neighbors</h3></div><Network size={21} /></div><div className="rivalry-network"><button className="rival-center" onClick={() => openProfile(player.Runner)}><FlagChip url={player['Flag URL']} /><strong>{player.Runner}</strong><small>#{player.Rank}</small></button>{rivals.map((rival) => <button className="rival-node" onClick={() => openProfile(rival.runner)} key={rival.runner}><FlagChip url={rival.flagUrl} /><span><strong>{rival.runner}</strong><small>{rival.shared} shared - {rival.close} close</small></span><em>{rival.wins}-{rival.losses}</em></button>)}</div></section><section className="lab-panel"><div className="lab-panel-title"><div><span>Next target</span><h3>Highest estimated score gains</h3></div><Target size={21} /></div><div className="target-list">{targets.slice(0, 6).map((target) => <button key={target.board.boardKey} onClick={() => updateScenarios(() => [{ boardKey: target.board.boardKey, place: target.proposedPlace }])}><span><strong>{gameNames[target.board.gameAbbr] || target.board.gameAbbr} - {target.board.category}</strong><small>{target.missing ? 'New board' : `Currently #${target.currentPlace}`} - target #{target.proposedPlace}</small></span><em>+{fmt(target.estimatedGain, 2)}</em></button>)}</div></section></div></div>;
}

function CareerPlayback({ rows, openProfile }: { rows: InsightHistoryRow[]; openProfile: (runner: string) => void }) {
  const periods = useMemo(() => Array.from(new Set(rows.map((row) => row.month?.slice(0, 7)).filter((month): month is string => Boolean(month)))).sort(), [rows]);
  const [index, setIndex] = useState(Math.max(0, periods.length - 1));
  const [playing, setPlaying] = useState(false);
  useEffect(() => {
    if (!playing || !periods.length) return;
    const timer = window.setInterval(() => setIndex((current) => { if (current >= periods.length - 1) { setPlaying(false); return current; } return current + 1; }), 1000);
    return () => window.clearInterval(timer);
  }, [periods.length, playing]);
  const period = periods[Math.min(index, periods.length - 1)] || '';
  const leaders = rows.filter((row) => row.month?.slice(0, 7) === period).sort((a, b) => a.rank - b.rank).slice(0, 12);
  const maxScore = Math.max(1, ...leaders.map((row) => Number(row.totalScore || 0)));
  const label = period ? new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${period}-01T00:00:00Z`)) : 'No history';
  return <div className="lab-stack"><section className="lab-band playback-controls"><button className="play-button" onClick={() => { if (index >= periods.length - 1) setIndex(0); setPlaying((value) => !value); }}>{playing ? <Pause size={17} /> : <Play size={17} />}{playing ? 'Pause' : 'Play history'}</button><div><strong>{label}</strong><span>{leaders.length} runners shown</span></div><input aria-label="Historical period" type="range" min="0" max={Math.max(0, periods.length - 1)} value={Math.min(index, Math.max(0, periods.length - 1))} onChange={(event) => { setPlaying(false); setIndex(Number(event.target.value)); }} /></section><section className="lab-panel race-panel"><div className="lab-panel-title"><div><span>Career playback</span><h3>The leaderboard at this moment</h3></div><Play size={21} /></div><div className="race-chart">{leaders.map((row) => <button key={row.runner} onClick={() => openProfile(row.runner)}><span className="race-rank">{row.rank}</span><strong>{row.runner}</strong><span className="race-track"><i style={{ width: `${Math.max(4, Number(row.totalScore || 0) / maxScore * 100)}%` }} /></span><em>{fmt(row.totalScore, 2)}</em></button>)}</div></section></div>;
}

function EngineMap({ player, players, runs, boards, runner, setRunner, gameNames }: { player: InsightPlayer; players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; runner: string; setRunner: (runner: string) => void; gameNames: Record<string, string> }) {
  const games = useMemo(() => Array.from(new Set(boards.map((board) => board.gameAbbr))), [boards]);
  const [game, setGame] = useState(games[0] || '');
  const [selectedKey, setSelectedKey] = useState('');
  const own = useMemo(() => new Map(runs.filter((run) => run.runner === player.Runner).map((run) => [run.boardKey, run])), [player.Runner, runs]);
  const shownBoards = boards.filter((board) => board.gameAbbr === (games.includes(game) ? game : games[0]));
  const selectedBoard = shownBoards.find((board) => board.boardKey === selectedKey) || shownBoards[0];
  const selectedRun = selectedBoard ? own.get(selectedBoard.boardKey) : null;
  const conquered = shownBoards.filter((board) => own.has(board.boardKey)).length;
  const medals = shownBoards.filter((board) => Number(own.get(board.boardKey)?.place || 999) <= 3).length;
  const records = shownBoards.filter((board) => Number(own.get(board.boardKey)?.place || 999) === 1).length;
  return <div className="lab-stack"><section className="lab-band map-toolbar"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Map for" /><div className="map-game-tabs">{games.map((item) => <button className={(games.includes(game) ? game : games[0]) === item ? 'active' : ''} key={item} onClick={() => { setGame(item); setSelectedKey(''); }}>{gameNames[item] || item}</button>)}</div></section><section className="lab-panel engine-map-panel"><div className="map-summary"><div><span>Conquered</span><strong>{conquered}/{shownBoards.length}</strong></div><div><span>Medals</span><strong>{medals}</strong></div><div><span>World records</span><strong>{records}</strong></div></div><div className="engine-map-grid">{shownBoards.map((board, index) => { const run = own.get(board.boardKey); const state = !run ? 'missing' : run.place === 1 ? 'wr' : run.place <= 3 ? 'medal' : 'ranked'; return <button className={`map-node ${state} ${selectedBoard?.boardKey === board.boardKey ? 'selected' : ''}`} key={board.boardKey} onClick={() => setSelectedKey(board.boardKey)}><span>{index + 1}</span><strong>{board.category}</strong><small>{[board.level, board.subcategory].filter(Boolean).join(' - ') || board.game}</small><em>{run ? `#${run.place}` : '?'}</em></button>; })}</div>{selectedBoard && <div className="map-detail"><span>{gameNames[selectedBoard.gameAbbr] || selectedBoard.gameAbbr}</span><strong>{insightBoardLabel(selectedBoard)}</strong><p>{selectedRun ? `${player.Runner} is #${selectedRun.place} of ${selectedRun.boardSize} with ${fmt(selectedRun.performancePoints, 2)} performance points.` : `${player.Runner} has not submitted to this ${selectedBoard.runCount}-runner board.`}</p></div>}</section></div>;
}

function EraHall({ rows, openProfile }: { rows: InsightHistoryRow[]; openProfile: (runner: string) => void }) {
  const careers = useMemo(() => eraHallOfFame(rows).slice(0, 40), [rows]);
  return <section className="lab-panel hall-panel"><div className="lab-panel-title"><div><span>Era-adjusted Hall of Fame</span><h3>Dominance relative to each season</h3></div><Crown size={22} /></div><p className="lab-explainer">A season index of 100 equals that year&apos;s performance leader. Career rating combines a runner&apos;s three strongest era indices plus a small longevity bonus.</p><div className="hall-table"><div className="hall-head"><span>Rank</span><span>Runner</span><span>Best season</span><span>Era index</span><span>Career rating</span></div>{careers.map((career, index) => <button key={career.runner} onClick={() => openProfile(career.runner)}><span>{index + 1}</span><strong>{career.runner}<small>{career.seasons} seasons</small></strong><span>{career.bestYear}<small>rank #{career.bestRank}</small></span><em>{fmt(career.bestIndex, 1)}</em><b>{fmt(career.rating, 1)}</b></button>)}</div></section>;
}

function EngineSeasons({ rows, openProfile }: { rows: InsightHistoryRow[]; openProfile: (runner: string) => void }) {
  const years = useMemo(() => Array.from(new Set(rows.map((row) => Number(row.month?.slice(0, 4) || 0)).filter(Boolean))).sort((a, b) => b - a), [rows]);
  const [year, setYear] = useState(years[0] || new Date().getUTCFullYear());
  const standings = useMemo(() => engineSeason(rows, years.includes(year) ? year : years[0]).slice(0, 40), [rows, year, years]);
  const activeYear = years.includes(year) ? year : years[0];
  const champion = standings[0];
  const mostWins = [...standings].sort((a, b) => b.wins - a.wins || b.points - a.points)[0];
  const ironRunner = [...standings].sort((a, b) => b.appearances - a.appearances || b.points - a.points)[0];
  return <div className="lab-stack"><section className="lab-band season-toolbar"><div><span>Engine season</span><strong>{activeYear}</strong></div><select value={activeYear} onChange={(event) => setYear(Number(event.target.value))}>{years.map((item) => <option value={item} key={item}>{item}</option>)}</select></section><div className="season-awards"><article><Trophy size={19} /><span>Championship leader</span><strong>{champion?.runner || '-'}</strong><small>{champion?.points || 0} points</small></article><article><Crown size={19} /><span>Most monthly wins</span><strong>{mostWins?.runner || '-'}</strong><small>{mostWins?.wins || 0} wins</small></article><article><Gauge size={19} /><span>Most active months</span><strong>{ironRunner?.runner || '-'}</strong><small>{ironRunner?.appearances || 0} appearances</small></article></div><section className="lab-panel season-panel"><div className="lab-panel-title"><div><span>Monthly championship points</span><h3>{activeYear} standings</h3></div><Trophy size={22} /></div><p className="lab-explainer">Each month awards 25-18-15-12-10-8-6-4-2-1 points to the top ten, creating a season-long championship alongside the main score.</p><div className="season-table">{standings.map((standing, index) => <button key={standing.runner} onClick={() => openProfile(standing.runner)}><span>{index + 1}</span><strong>{standing.runner}<small>{standing.appearances} months - {standing.podiums} podiums</small></strong><em>{standing.wins} wins</em><b>{standing.points}</b></button>)}</div></section></div>;
}
