'use client';

import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CalendarDays, Clock3, Crown, FlaskConical, Gauge, Map as MapIcon, Network, Pause, Play, Plus, Route, Search, Sparkles, Target, Trash2, Trophy, X } from 'lucide-react';
import {
  baseGameKey,
  careerRace,
  dynastyTable,
  eligibleBoardsForRunner,
  eligibleSetupsForRunner,
  engineSeason,
  formatRunTime,
  insightBoardLabel,
  momentumReport,
  nextTargets,
  parseRunTime,
  projectedRank,
  projectedPlaceForTime,
  rankChasePlan,
  runnerArchetype,
  runnerRivalries,
  scenarioSeconds,
  setupKey,
  simulateRunnerScore,
  targetInstruction,
  type InsightBoard,
  type InsightHistoryRow,
  type InsightPlayer,
  type InsightRun,
  type RaceMetric,
} from './insights';

type LabMode = 'simulator' | 'milestones' | 'momentum' | 'timeline' | 'map' | 'hall' | 'seasons';
type Scenario = { boardKey: string; time: string; setupKey: string };

const labModes: Array<{ key: LabMode; label: string; icon: typeof FlaskConical }> = [
  { key: 'simulator', label: 'Runner Lab', icon: FlaskConical },
  { key: 'milestones', label: 'Milestones', icon: Target },
  { key: 'momentum', label: 'Momentum', icon: Gauge },
  { key: 'timeline', label: 'Career Race', icon: Play },
  { key: 'map', label: 'Engine Map', icon: MapIcon },
  { key: 'hall', label: 'Dynasties', icon: Crown },
  { key: 'seasons', label: 'Seasons', icon: Trophy },
];

function fmt(value: number, decimals = 0) {
  return new Intl.NumberFormat('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals }).format(Number(value || 0));
}

function targetMeta(target: ReturnType<typeof nextTargets>[number]) {
  const cadence = target.cadenceFps ? `${(1000 / target.cadenceFps).toFixed(3)} ms/frame` : target.cadenceLabel;
  const timeToFind = target.currentSeconds && target.currentSeconds > target.goalSeconds ? formatRunTime(target.currentSeconds - target.goalSeconds) : '';
  const effort = target.framesToFind && target.framesToFind <= 300 ? `${target.framesToFind} frame${target.framesToFind === 1 ? '' : 's'} to find` : timeToFind ? `${timeToFind} to find` : target.missing ? 'new category' : 'accepted benchmark';
  return `${target.setupLabel} · ${target.difficulty} · ${effort} · ${cadence}`;
}

function FlagChip({ url }: { url: string | null }) {
  // Flag URLs are generated by the site data pipeline and served locally.
  // eslint-disable-next-line @next/next/no-img-element
  return url ? <img className="flag" src={url} alt="" loading="lazy" decoding="async" /> : <span className="flag flag-placeholder" />;
}

function RunnerSearch({ players, value, onChange, label = 'Runner' }: { players: InsightPlayer[]; value: string; onChange: (runner: string) => void; label?: string }) {
  const [query, setQuery] = useState(value);
  const [open, setOpen] = useState(false);
  const matches = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase();
    return players.filter((player) => !needle || player.Runner.toLocaleLowerCase().includes(needle)).slice(0, 12);
  }, [players, query]);
  const shownValue = open ? query : value;
  return <label className="lab-runner-field"><span>{label}</span><div className="lab-runner-input"><Search size={16} /><input value={shownValue} onFocus={() => { setOpen(true); setQuery(''); }} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} onBlur={() => setTimeout(() => setOpen(false), 120)} placeholder="Search runners" />{open && <div className="lab-runner-results">{matches.map((player) => <button type="button" key={player.Runner} onMouseDown={(event) => { event.preventDefault(); onChange(player.Runner); setQuery(player.Runner); setOpen(false); }}><FlagChip url={player['Flag URL']} /><span><strong>{player.Runner}</strong><small>{player.Country || 'Unlisted country'}</small></span><em>#{player.Rank}</em></button>)}{!matches.length && <p>No runners found.</p>}</div>}</div></label>;
}

export default function InsightsLab({ players, runs, boards, yearly, gameNames, openProfile }: { players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; yearly: InsightHistoryRow[]; gameNames: Record<string, string>; openProfile: (runner: string) => void }) {
  const [mode, setMode] = useState<LabMode>('simulator');
  const [runner, setRunner] = useState(players[0]?.Runner || '');
  const selected = players.find((player) => player.Runner === runner) || players[0] || null;

  return <section className="view-section insights-view"><div className="page-heading lab-heading"><div><p className="eyebrow">Explore the engine differently</p><h2>Insights Lab</h2></div><Sparkles size={28} /></div><nav className="lab-tabs" aria-label="Insights Lab tools">{labModes.map(({ key, label, icon: Icon }) => <button key={key} className={mode === key ? 'active' : ''} onClick={() => setMode(key)}><Icon size={16} />{label}</button>)}</nav>{mode === 'simulator' && selected && <RunnerLab player={selected} players={players} runs={runs} boards={boards} runner={runner} setRunner={setRunner} gameNames={gameNames} openProfile={openProfile} />}{mode === 'milestones' && selected && <MilestoneWatch player={selected} players={players} runs={runs} boards={boards} runner={runner} setRunner={setRunner} gameNames={gameNames} openProfile={openProfile} openRunnerLab={() => setMode('simulator')} />}{mode === 'momentum' && <MomentumLab players={players} runs={runs} runner={runner} setRunner={setRunner} openProfile={openProfile} />}{mode === 'timeline' && selected && <CareerRace player={selected} players={players} runs={runs} runner={runner} setRunner={setRunner} gameNames={gameNames} openProfile={openProfile} />}{mode === 'map' && selected && <EngineMap player={selected} players={players} runs={runs} boards={boards} runner={runner} setRunner={setRunner} gameNames={gameNames} />}{mode === 'hall' && <Dynasties rows={yearly} openProfile={openProfile} />}{mode === 'seasons' && <EngineSeasons players={players} runs={runs} openProfile={openProfile} />}</section>;
}

function displayDate(value: string | null) {
  if (!value) return 'No dated activity';
  return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(value));
}

function MilestoneWatch({ player, players, runs, boards, runner, setRunner, gameNames, openProfile, openRunnerLab }: { player: InsightPlayer; players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; runner: string; setRunner: (runner: string) => void; gameNames: Record<string, string>; openProfile: (runner: string) => void; openRunnerLab: () => void }) {
  const targets = useMemo(() => nextTargets(player, runs, boards, 16), [boards, player, runs]);
  const ownGames = useMemo(() => new Set(runs.filter((run) => run.runner === player.Runner).map((run) => baseGameKey(run.gameToggle || run.gameAbbr))), [player.Runner, runs]);
  const nextRank = players.find((item) => Number(item.Rank) === Number(player.Rank) - 1);
  const rankGap = nextRank ? Math.max(0, Number(nextRank['Total Score']) - Number(player['Total Score']) + 0.01) : 0;
  const bestTarget = targets[0] || null;
  const medalTarget = targets.find((target) => target.proposedPlace <= 3) || null;
  const newGameTarget = targets.find((target) => target.missing && !ownGames.has(baseGameKey(target.board.gameAbbr))) || targets.find((target) => target.missing) || null;
  const cards = [
    { label: 'Overall rank', title: player.Rank === 1 ? 'At the top' : `Reach #${Math.max(1, Number(player.Rank) - 1)}`, value: player.Rank === 1 ? '#1' : `+${fmt(rankGap, 2)} pts`, detail: nextRank ? `Clear ${nextRank.Runner}'s current score` : 'No higher ranked runner in this view', tone: 'red' },
    { label: 'Best score route', title: bestTarget ? `${gameNames[bestTarget.board.gameAbbr] || bestTarget.board.gameAbbr} · ${insightBoardLabel(bestTarget.board)}` : 'No route found', value: bestTarget ? `+${fmt(bestTarget.estimatedGain, 2)}` : '—', detail: bestTarget ? `${targetInstruction(bestTarget)} for about #${bestTarget.proposedPlace}` : 'More eligible board data is needed', tone: 'blue' },
    { label: 'Next medal', title: medalTarget ? `${gameNames[medalTarget.board.gameAbbr] || medalTarget.board.gameAbbr} · ${insightBoardLabel(medalTarget.board)}` : 'No medal route found', value: medalTarget ? `#${medalTarget.proposedPlace}` : '—', detail: medalTarget ? `${medalTarget.difficulty} · +${fmt(medalTarget.estimatedGain, 2)} estimated points` : 'Current path has no proof-backed podium target', tone: 'gold' },
    { label: 'Engine expansion', title: newGameTarget ? gameNames[newGameTarget.board.gameAbbr] || newGameTarget.board.gameAbbr : 'Portfolio complete', value: newGameTarget ? `+${fmt(newGameTarget.estimatedGain, 2)}` : `${ownGames.size} games`, detail: newGameTarget ? `${insightBoardLabel(newGameTarget.board)} · new-category benchmark` : 'No additional eligible game target found', tone: 'green' },
  ];

  return <div className="lab-stack">
    <section className="lab-band milestone-toolbar"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Watch milestones for" /><button className="profile-jump" onClick={() => { openProfile(player.Runner); }}>Open full profile</button><button className="profile-jump" onClick={openRunnerLab}>Open Runner Lab</button></section>
    <section className="lab-panel milestone-panel"><div className="lab-panel-title"><div><span>Milestone Watch</span><h3>Concrete next steps for {player.Runner}</h3></div><Target size={22} /></div><p className="lab-explainer">Targets follow this runner&apos;s accepted hardware path and use frame-aware benchmarks from the included leaderboards. Points are estimates; Speedrun.com rules remain authoritative.</p><div className="milestone-grid">{cards.map((card) => <article className={`milestone-card ${card.tone}`} key={card.label}><span>{card.label}</span><strong>{card.title}</strong><b>{card.value}</b><small>{card.detail}</small></article>)}</div><div className="milestone-heading"><div><span>Priority queue</span><h4>Proof-backed goals</h4></div><span>{targets.length} candidates</span></div><div className="milestone-list">{targets.slice(0, 10).map((target, index) => <button key={`${target.board.boardKey}-${target.setupKey}`} onClick={openRunnerLab}><span className="milestone-index">{index + 1}</span><span className="milestone-copy"><strong>{gameNames[target.board.gameAbbr] || target.board.gameAbbr} · {insightBoardLabel(target.board)}</strong><small>{target.goalLabel} · {targetInstruction(target)} · {targetMeta(target)}</small></span><em>+{fmt(target.estimatedGain, 2)}<small>estimated</small></em></button>)}{!targets.length && <div className="rank-chase-empty"><Target size={20} /><span>No proof-backed targets are available for this runner under the current filters.</span></div>}</div></section>
  </div>;
}

function MomentumLab({ players, runs, runner, setRunner, openProfile }: { players: InsightPlayer[]; runs: InsightRun[]; runner: string; setRunner: (runner: string) => void; openProfile: (runner: string) => void }) {
  const [days, setDays] = useState(90);
  const report = useMemo(() => momentumReport(players, runs, days), [days, players, runs]);
  const activeEntries = report.entries.filter((entry) => entry.recentRuns > 0);
  const selected = report.entries.find((entry) => entry.runner === runner) || report.entries[0] || null;
  const pace = selected ? selected.scoreGain * 30 / report.days : 0;
  return <div className="lab-stack">
    <section className="lab-band momentum-toolbar"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Focus runner" /><label className="lab-select-field"><span>Window</span><select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="180">Last 180 days</option><option value="365">Last year</option></select></label><div className="momentum-asof"><span>Measured through</span><strong>{displayDate(report.asOf)}</strong><small>Verified date, with entered run date as fallback</small></div></section>
    <section className="lab-panel momentum-panel"><div className="lab-panel-title"><div><span>Momentum</span><h3>Who is adding the most current score?</h3></div><Gauge size={22} /></div><p className="lab-explainer">Momentum is ranked by the estimated contribution of each runner&apos;s current, dated runs inside the selected window. It applies the same performance, volume, and variety rules as the leaderboard, using today&apos;s board placements.</p>{selected && <div className="momentum-focus"><button onClick={() => openProfile(selected.runner)}><FlagChip url={selected.flagUrl} /><span><strong>{selected.runner}</strong><small>Current rank #{selected.rank} · {selected.recentRuns} recent runs</small></span></button><div><span>Window contribution</span><strong>+{fmt(selected.scoreGain, 2)}</strong><small>{selected.performanceGain > 0 ? `${fmt(selected.performanceGain, 2)} performance` : 'No dated score contribution'}</small></div><div><span>30-day pace</span><strong>+{fmt(pace, 2)}</strong><small>{selected.recentBoards} new boards · {selected.recentGames} new games</small></div><div><span>Rank reconstruction</span><strong>{selected.rankShift > 0 ? `+${selected.rankShift}` : selected.rankShift < 0 ? `${selected.rankShift}` : '—'}</strong><small>{selected.rankBefore ? `Was about #${selected.rankBefore} at window start` : 'Not enough dated history'}</small></div></div>}<div className="momentum-heading"><div><span>Fastest current growth</span><h4>Top dated contributors</h4></div><span>{activeEntries.length} active runners</span></div><div className="momentum-list">{activeEntries.slice(0, 20).map((entry, index) => <button key={entry.runner} className={entry.runner === runner ? 'selected' : ''} onClick={() => setRunner(entry.runner)}><span className="momentum-rank">{index + 1}</span><FlagChip url={entry.flagUrl} /><span className="momentum-copy"><strong>{entry.runner}</strong><small>#{entry.rank} now · {entry.recentRuns} runs · {entry.recentBoards} new boards · {entry.recentGames} new games</small></span><span className="momentum-value"><b>+{fmt(entry.scoreGain, 2)}</b><small>+{fmt(entry.scoreGain * 30 / report.days, 2)} / 30d</small></span></button>)}{!activeEntries.length && <div className="rank-chase-empty"><Gauge size={20} /><span>No dated runs fall inside this window.</span></div>}</div>{selected && selected.undatedRuns > 0 && <p className="momentum-note">{selected.undatedRuns} current run{selected.undatedRuns === 1 ? '' : 's'} for {selected.runner} lack a usable verified or entered date and are excluded from this trend.</p>}</section>
  </div>;
}

function RunnerLab({ player, players, runs, boards, runner, setRunner, gameNames, openProfile }: { player: InsightPlayer; players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; runner: string; setRunner: (runner: string) => void; gameNames: Record<string, string>; openProfile: (runner: string) => void }) {
  const pathBoards = useMemo(() => eligibleBoardsForRunner(player.Runner, boards, runs), [boards, player.Runner, runs]);
  const boardMap = useMemo(() => new Map(pathBoards.map((board) => [board.boardKey, board])), [pathBoards]);
  const targets = useMemo(() => nextTargets(player, runs, boards, 8), [boards, player, runs]);
  const rivals = useMemo(() => runnerRivalries(player, runs, players, 5), [player, players, runs]);
  const archetype = useMemo(() => runnerArchetype(player), [player]);
  const defaultScenario = useMemo(() => targets[0] ? [{ boardKey: targets[0].board.boardKey, time: targets[0].goalTime, setupKey: targets[0].setupKey }] : [], [targets]);
  const [scenarioState, setScenarioState] = useState<{ runner: string; rows: Scenario[] }>({ runner: player.Runner, rows: defaultScenario });
  const scenarios = scenarioState.runner === player.Runner ? scenarioState.rows : defaultScenario;
  const timedScenarios = useMemo(() => scenarios.map((scenario) => ({ boardKey: scenario.boardKey, seconds: parseRunTime(scenario.time), setupKey: scenario.setupKey })), [scenarios]);
  const projection = useMemo(() => simulateRunnerScore(player, runs, boards, timedScenarios), [boards, player, runs, timedScenarios]);
  const newRank = projectedRank(players, player.Runner, projection.score);
  const defaultChaseRank = Math.max(1, Number(player.Rank || 1) - 5);
  const [chaseState, setChaseState] = useState({ runner: player.Runner, rank: defaultChaseRank });
  const chaseRank = chaseState.runner === player.Runner ? Math.min(player.Rank, chaseState.rank) : defaultChaseRank;
  const chase = useMemo(() => rankChasePlan(player, players, runs, boards, chaseRank, 8), [boards, chaseRank, player, players, runs]);

  function updateScenarios(updater: (rows: Scenario[]) => Scenario[]) {
    setScenarioState((current) => ({ runner: player.Runner, rows: updater(current.runner === player.Runner ? current.rows : defaultScenario) }));
  }

  function suggestedScenario(boardKey: string): Scenario {
    const target = targets.find((item) => item.board.boardKey === boardKey);
    if (target) return { boardKey, time: target.goalTime, setupKey: target.setupKey };
    const board = boardMap.get(boardKey);
    if (!board) return { boardKey, time: '0:00.000', setupKey: '' };
    const setups = eligibleSetupsForRunner(player.Runner, board, runs);
    const existing = runs.find((run) => run.runner === player.Runner && run.boardKey === boardKey);
    const existingKey = existing ? setupKey(existing.platform, existing.hardware) : '';
    const setup = setups.find((item) => item.key === existingKey) || setups[0];
    if (existing?.seconds && setup) return { boardKey, time: formatRunTime(existing.seconds), setupKey: setup.key };
    const boardTimes = runs.filter((run) => run.boardKey === boardKey && run.seconds > 0 && setupKey(run.platform, run.hardware) === setup?.key).map((run) => run.seconds).sort((a, b) => a - b);
    return { boardKey, time: boardTimes.length ? formatRunTime(boardTimes[Math.floor(boardTimes.length / 2)]) : '0:00.000', setupKey: setup?.key || '' };
  }

  return <div className="lab-stack">
    <section className="lab-band runner-lab-header"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Run the numbers for" /><button className="profile-jump" onClick={() => openProfile(player.Runner)}>Open full profile</button></section>
    <div className="lab-split">
      <section className="lab-panel simulator-panel">
        <div className="lab-panel-title"><div><span>What-if simulator</span><h3>Enter the times you want to achieve</h3></div><FlaskConical size={22} /></div>
        <p className="lab-explainer">Boards and setups follow this runner&apos;s demonstrated hardware path. Known platform cadences snap entered times to a real frame; every suggested target is copied from an accepted run.</p>
        <div className="simulation-score"><div><span>Current</span><strong>#{player.Rank}</strong><small>{fmt(player['Total Score'], 2)} points</small></div><b>to</b><div className={newRank < player.Rank ? 'improved' : ''}><span>Projected</span><strong>#{newRank}</strong><small>{fmt(projection.score, 2)} points</small></div><em>{projection.delta >= 0 ? '+' : ''}{fmt(projection.delta, 2)}</em></div>
        <div className="scenario-list">{scenarios.map((scenario, index) => {
          const board = boardMap.get(scenario.boardKey);
          const setups = board ? eligibleSetupsForRunner(player.Runner, board, runs) : [];
          const setup = setups.find((item) => item.key === scenario.setupKey) || setups[0] || null;
          const enteredSeconds = parseRunTime(scenario.time);
          const adjustedSeconds = board ? scenarioSeconds(player.Runner, board, scenario.setupKey, enteredSeconds, runs) : enteredSeconds;
          const place = projectedPlaceForTime(player.Runner, scenario.boardKey, adjustedSeconds, runs);
          return <div className="scenario-row" key={`${player.Runner}-${index}`}><label><span>Board</span><select value={scenario.boardKey} onChange={(event) => updateScenarios((rows) => rows.map((row, rowIndex) => rowIndex === index ? suggestedScenario(event.target.value) : row))}>{pathBoards.map((item) => <option value={item.boardKey} key={item.boardKey}>{gameNames[item.gameAbbr] || item.gameAbbr} - {insightBoardLabel(item)}</option>)}</select></label><label><span>Setup</span><select value={setup?.key || ''} onChange={(event) => updateScenarios((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, setupKey: event.target.value } : row))}>{setups.map((item) => <option value={item.key} key={item.key}>{item.label}</option>)}</select><small>{setup ? `${setup.cadenceLabel} · ${setup.sample} accepted` : 'No demonstrated setup'}</small></label><label className="time-field"><span>Target time</span><input type="text" inputMode="decimal" value={scenario.time} placeholder="4:55.000" onChange={(event) => updateScenarios((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, time: event.target.value } : row))} /><small>{place ? `Frame target ${formatRunTime(adjustedSeconds)} · about #${place}` : 'Enter m:ss.mmm'}</small></label><button className="icon-button" title="Remove scenario" aria-label="Remove scenario" onClick={() => updateScenarios((rows) => rows.filter((_, rowIndex) => rowIndex !== index))}><Trash2 size={15} /></button></div>;
        })}</div>
        <button className="add-scenario" disabled={scenarios.length >= 8 || !pathBoards.length} onClick={() => updateScenarios((rows) => { const next = targets.find((target) => !rows.some((row) => row.boardKey === target.board.boardKey)); const boardKey = next?.board.boardKey || pathBoards.find((board) => !rows.some((row) => row.boardKey === board.boardKey))?.boardKey || pathBoards[0]?.boardKey || ''; return [...rows, suggestedScenario(boardKey)]; })}><Plus size={15} /> Add target time</button>
        <div className="projection-breakdown"><span>Performance <strong>{projection.performanceDelta >= 0 ? '+' : ''}{fmt(projection.performanceDelta, 2)}</strong></span><span>Volume <strong>+{fmt(projection.volumeDelta, 2)}</strong></span><span>Variety <strong>{projection.varietyDelta >= 0 ? '+' : ''}{fmt(projection.varietyDelta, 2)}</strong></span></div>
      </section>
      <aside className="lab-panel archetype-panel"><div className="archetype-mark"><Sparkles size={20} /><span>Runner archetype</span></div><h3>{archetype.name}</h3><p>{archetype.detail}</p><div className="trait-list">{archetype.traits.map((trait) => <span key={trait}>{trait}</span>)}</div><dl><div><dt>Current rank</dt><dd>#{player.Rank}</dd></div><div><dt>Boards</dt><dd>{player['Unique Boards']}</dd></div><div><dt>WRs</dt><dd>{player.WRs}</dd></div></dl></aside>
    </div>
    <section className="lab-panel rank-chase-panel">
      <div className="lab-panel-title"><div><span>Rank chase planner</span><h3>Turn an overall-rank goal into a timed route</h3></div><Route size={22} /></div>
      <div className="rank-chase-toolbar"><label><span>Desired overall rank</span><input type="number" min="1" max={Math.max(1, player.Rank)} value={chaseRank} disabled={player.Rank === 1} onChange={(event) => setChaseState({ runner: player.Runner, rank: Math.max(1, Math.min(player.Rank, Number(event.target.value || 1))) })} /></label><div><span>Points to catch</span><strong>{chase.requiredGain > 0 ? `+${fmt(chase.requiredGain, 2)}` : 'Already there'}</strong><small>{chase.targetScore > player['Total Score'] ? `${fmt(chase.targetScore, 2)} points clears the line` : `${player.Runner} already owns this position`}</small></div><div><span>Planner result</span><strong>{chase.steps.length ? `Projected #${chase.projectedRank}` : `Current #${player.Rank}`}</strong><small>{chase.reached ? `${chase.steps.length} route-aligned goal${chase.steps.length === 1 ? '' : 's'} found` : chase.remainingGap > 0 ? `${fmt(chase.remainingGap, 2)} points still needed` : 'Choose a higher position'}</small></div><button className="profile-jump" disabled={!chase.steps.length} onClick={() => updateScenarios(() => chase.steps.map((step) => ({ boardKey: step.target.board.boardKey, time: step.target.goalTime, setupKey: step.target.setupKey })))}>Load route into simulator</button></div>
      {chase.steps.length ? <div className="rank-chase-route">{chase.steps.map((step, index) => <article key={step.target.board.boardKey} title={targetMeta(step.target)}><span>{index + 1}</span><div><strong>{gameNames[step.target.board.gameAbbr] || step.target.board.gameAbbr} - {insightBoardLabel(step.target.board)}</strong><small>{step.target.goalLabel}: {targetInstruction(step.target)} for about #{step.target.proposedPlace}</small><small className="target-meta">{targetMeta(step.target)}</small></div><em>+{fmt(step.gain, 2)}</em><b>then #{step.projectedRank}</b></article>)}</div> : <div className="rank-chase-empty"><Trophy size={20} /><span>{player.Rank === 1 ? `${player.Runner} is already at the top.` : 'No proof-backed route on this runner\'s demonstrated setups reaches that rank yet.'}</span></div>}
      <p className="rank-chase-note">Routes are ranked by score gain versus placement difficulty. They never invent a sub-frame time, recommend an unseen setup, or promise that a sparse board is easy. Platform eligibility is inferred from accepted runs; the linked Speedrun.com rules remain authoritative.</p>
    </section>
    <div className="lab-split lower">
      <section className="lab-panel"><div className="lab-panel-title"><div><span>Rivalry network</span><h3>Closest competitive neighbors</h3></div><Network size={21} /></div><p className="lab-explainer">Rivals are runners who share many boards with you, especially where the placements are close.</p><div className="rivalry-network"><button className="rival-center" onClick={() => openProfile(player.Runner)}><FlagChip url={player['Flag URL']} /><strong>{player.Runner}</strong><small>#{player.Rank}</small></button>{rivals.map((rival) => <button className="rival-node" onClick={() => openProfile(rival.runner)} key={rival.runner}><FlagChip url={rival.flagUrl} /><span><strong>{rival.runner}</strong><small>{rival.shared} shared boards · {rival.close} within 3 places</small></span><span className="rival-record"><b>You lead {rival.wins}</b><small>You trail {rival.losses}</small></span></button>)}</div></section>
      <section className="lab-panel"><div className="lab-panel-title"><div><span>Concrete goals</span><h3>Best route-aligned score gains</h3></div><Target size={21} /></div><p className="lab-explainer">Every target is an accepted time on a setup this runner already uses. New categories need at least three accepted setup-matched runs before they can be recommended.</p><div className="target-list">{targets.slice(0, 6).map((target) => <button key={target.board.boardKey} title={targetMeta(target)} onClick={() => updateScenarios(() => [{ boardKey: target.board.boardKey, time: target.goalTime, setupKey: target.setupKey }])}><Clock3 size={15} /><span><strong>{gameNames[target.board.gameAbbr] || target.board.gameAbbr} - {insightBoardLabel(target.board)}</strong><small>{target.goalLabel}: {targetInstruction(target)} for about #{target.proposedPlace}</small><small className="target-meta">{targetMeta(target)}</small></span><em>+{fmt(target.estimatedGain, 2)}</em></button>)}{!targets.length && <p className="rank-chase-empty">No proof-backed goal is available on this runner&apos;s demonstrated setups.</p>}</div></section>
    </div>
  </div>;
}

const RACE_COLORS = ['#ef5a4f', '#69abe0', '#f0bd39', '#73c494'];

function raceValue(point: ReturnType<typeof careerRace>['series'][number]['points'][number], metric: RaceMetric) {
  if (metric === 'performance') return point.performance;
  if (metric === 'runs') return point.runs;
  if (metric === 'games') return point.games;
  return point.score;
}

function CareerRace({ player, players, runs, runner, setRunner, gameNames, openProfile }: { player: InsightPlayer; players: InsightPlayer[]; runs: InsightRun[]; runner: string; setRunner: (runner: string) => void; gameNames: Record<string, string>; openProfile: (runner: string) => void }) {
  const defaultRoster = useMemo(() => [player.Runner, ...runnerRivalries(player, runs, players, 2).map((rival) => rival.runner)].filter((name, index, names) => names.indexOf(name) === index), [player, players, runs]);
  const [rosterState, setRosterState] = useState({ anchor: player.Runner, names: defaultRoster });
  const roster = rosterState.anchor === player.Runner ? rosterState.names : defaultRoster;
  const race = useMemo(() => careerRace(players, runs, roster, 2015), [players, roster, runs]);
  const [metric, setMetric] = useState<RaceMetric>('score');
  const [playback, setPlayback] = useState({ key: roster.join('|'), index: Math.max(0, race.periods.length - 1), playing: false });
  const raceKey = roster.join('|');
  const index = playback.key === raceKey ? Math.min(playback.index, Math.max(0, race.periods.length - 1)) : Math.max(0, race.periods.length - 1);
  const playing = playback.key === raceKey && playback.playing;

  useEffect(() => {
    if (!playing || !race.periods.length) return;
    const timer = window.setInterval(() => setPlayback((current) => { const currentIndex = current.key === raceKey ? current.index : 0; if (currentIndex >= race.periods.length - 1) return { key: raceKey, index: currentIndex, playing: false }; return { key: raceKey, index: currentIndex + 1, playing: true }; }), 170);
    return () => window.clearInterval(timer);
  }, [playing, race.periods.length, raceKey]);

  const period = race.periods[index] || '';
  const label = period ? new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${period}-01T00:00:00Z`)) : 'No history';
  const racers = race.series.map((series, colorIndex) => ({ series, point: series.points[index], previous: series.points[Math.max(0, index - 1)], color: RACE_COLORS[colorIndex] })).sort((a, b) => raceValue(b.point, metric) - raceValue(a.point, metric));
  const maxCurrent = Math.max(1, ...racers.map((racer) => raceValue(racer.point, metric)));
  const maxChart = Math.max(1, ...race.series.flatMap((series) => series.points.slice(0, index + 1).map((point) => raceValue(point, metric))));
  const previousLeader = index > 0 ? [...race.series].sort((a, b) => raceValue(b.points[index - 1], metric) - raceValue(a.points[index - 1], metric))[0]?.runner : '';
  const leaderChanged = index > 0 && racers[0]?.series.runner !== previousLeader && raceValue(racers[0]?.point, metric) > 0;
  const additions = racers.flatMap((racer) => racer.point.newRuns.map((run) => ({ run, runner: racer.series.runner, color: racer.color }))).sort((a, b) => b.run.performancePoints - a.run.performancePoints);
  const milestones = racers.flatMap((racer) => {
    const items: string[] = [];
    if (!racer.previous.runs && racer.point.runs) items.push('first dated run');
    [1000, 2500, 5000].forEach((threshold) => { if (racer.previous.score < threshold && racer.point.score >= threshold) items.push(`crosses ${fmt(threshold)} points`); });
    [100, 50, 25, 10, 5, 1].forEach((rank) => { if (racer.point.fieldRank && racer.point.fieldRank <= rank && (!racer.previous.fieldRank || racer.previous.fieldRank > rank)) items.push(`enters reconstructed top ${rank}`); });
    if (racer.point.games > racer.previous.games) items.push(`reaches ${racer.point.games} game${racer.point.games === 1 ? '' : 's'}`);
    return items.map((text) => ({ runner: racer.series.runner, text, color: racer.color }));
  });

  function setRoster(names: string[]) {
    setRosterState({ anchor: player.Runner, names: names.slice(0, 4) });
  }

  return <div className="lab-stack">
    <section className="lab-band race-roster-toolbar"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Anchor runner" />{roster.length < 4 ? <RunnerSearch players={players.filter((item) => !roster.includes(item.Runner))} value="" onChange={(name) => !roster.includes(name) && setRoster([...roster, name])} label="Add a comparison" /> : <div className="race-limit"><span>Comparison roster</span><strong>Four runners selected</strong></div>}<div className="race-roster">{roster.map((name, colorIndex) => <span style={{ borderColor: RACE_COLORS[colorIndex] }} key={name}><i style={{ background: RACE_COLORS[colorIndex] }} />{name}{colorIndex > 0 && <button title={`Remove ${name}`} aria-label={`Remove ${name}`} onClick={() => setRoster(roster.filter((item) => item !== name))}><X size={12} /></button>}</span>)}</div></section>
    <section className="lab-band playback-controls race-controls"><button className="play-button" onClick={() => setPlayback({ key: raceKey, index: index >= race.periods.length - 1 ? 0 : index, playing: !playing })}>{playing ? <Pause size={17} /> : <Play size={17} />}{playing ? 'Pause' : 'Race from 2015'}</button><div><strong>{label}</strong><span>{leaderChanged ? `${racers[0].series.runner} takes the comparison lead` : `${additions.length} selected-runner addition${additions.length === 1 ? '' : 's'}`}</span></div><input aria-label="Career race period" type="range" min="0" max={Math.max(0, race.periods.length - 1)} value={index} onChange={(event) => setPlayback({ key: raceKey, index: Number(event.target.value), playing: false })} /><div className="race-metrics">{([{ key: 'score', label: 'Total' }, { key: 'performance', label: 'Performance' }, { key: 'runs', label: 'Runs' }, { key: 'games', label: 'Games' }] as Array<{ key: RaceMetric; label: string }>).map((item) => <button className={metric === item.key ? 'active' : ''} key={item.key} onClick={() => setMetric(item.key)}>{item.label}</button>)}</div></section>
    <section className="lab-panel career-race-panel"><div className="lab-panel-title"><div><span>Career Race</span><h3>Current portfolios reconstructed from January 2015</h3></div><BarChart3 size={22} /></div><p className="lab-explainer">Every frame includes current non-obsolete runs performed by that month. Whole-field rank is reconstructed with today&apos;s board sizes and placements; it is not a claim about the exact leaderboard that existed then.</p>
      <div className="race-visual"><svg viewBox="0 0 1000 250" preserveAspectRatio="none" role="img" aria-label={`${metric} comparison through ${label}`}><g className="race-grid"><line x1="0" x2="1000" y1="62.5" y2="62.5" /><line x1="0" x2="1000" y1="125" y2="125" /><line x1="0" x2="1000" y1="187.5" y2="187.5" /></g>{race.series.map((series, seriesIndex) => { const points = series.points.slice(0, index + 1).map((point, pointIndex) => `${race.periods.length > 1 ? pointIndex / (race.periods.length - 1) * 1000 : 0},${244 - raceValue(point, metric) / maxChart * 232}`).join(' '); return <polyline key={series.runner} points={points} fill="none" stroke={RACE_COLORS[seriesIndex]} strokeWidth="5" vectorEffect="non-scaling-stroke" />; })}<line className="race-now" x1={race.periods.length > 1 ? index / (race.periods.length - 1) * 1000 : 0} x2={race.periods.length > 1 ? index / (race.periods.length - 1) * 1000 : 0} y1="0" y2="250" /></svg><div className="race-axis"><span>Jan 2015</span><strong>{label}</strong><span>{race.periods.at(-1)}</span></div></div>
      <div className="race-standings">{racers.map((racer, racerIndex) => <button key={racer.series.runner} onClick={() => openProfile(racer.series.runner)}><span className="race-position" style={{ borderColor: racer.color }}>{racerIndex + 1}</span><FlagChip url={racer.series.flagUrl} /><div><strong>{racer.series.runner}</strong><small>{racer.point.fieldRank ? `Reconstructed overall #${racer.point.fieldRank}` : 'No dated runs yet'} · {racer.point.runs} runs · {racer.point.games} games</small></div><span className="race-progress"><i style={{ width: `${raceValue(racer.point, metric) / maxCurrent * 100}%`, background: racer.color }} /></span><em>{fmt(raceValue(racer.point, metric), metric === 'score' || metric === 'performance' ? 2 : 0)}<small>{racer.point.scoreGain > 0 ? `+${fmt(racer.point.scoreGain, 2)} score this month` : 'no score change'}</small></em></button>)}</div>
      <div className="race-moments"><section><div className="career-events-head"><span>Runs added in {label}</span><strong>{additions.length} across selected runners</strong></div>{additions.slice(0, 6).map(({ run, runner: runRunner, color }) => <article key={`${runRunner}-${run.boardKey}`} style={{ borderLeftColor: color }}><span>{runRunner}</span><strong>{gameNames[run.gameAbbr] || run.gameAbbr} - {insightBoardLabel({ category: run.category, level: run.level, subcategory: run.subcategory })}</strong><em>{run.time || formatRunTime(run.seconds)}</em></article>)}{!additions.length && <p>No selected runner added a current portfolio run this month.</p>}</section><section><div className="career-events-head"><span>Milestones</span><strong>{milestones.length} this month</strong></div>{milestones.slice(0, 8).map((milestone, milestoneIndex) => <article key={`${milestone.runner}-${milestone.text}-${milestoneIndex}`} style={{ borderLeftColor: milestone.color }}><span>{milestone.runner}</span><strong>{milestone.text}</strong></article>)}{!milestones.length && <p>No reconstructed milestone this month.</p>}</section></div>
    </section>
  </div>;
}

function EngineMap({ player, players, runs, boards, runner, setRunner, gameNames }: { player: InsightPlayer; players: InsightPlayer[]; runs: InsightRun[]; boards: InsightBoard[]; runner: string; setRunner: (runner: string) => void; gameNames: Record<string, string> }) {
  const games = useMemo(() => Array.from(new Set(boards.map((board) => board.gameAbbr))), [boards]);
  const [game, setGame] = useState(games[0] || '');
  const [selectedKey, setSelectedKey] = useState('');
  const own = useMemo(() => new Map(runs.filter((run) => run.runner === player.Runner).map((run) => [run.boardKey, run])), [player.Runner, runs]);
  const shownBoards = boards.filter((board) => board.gameAbbr === (games.includes(game) ? game : games[0]));
  const selectedBoard = shownBoards.find((board) => board.boardKey === selectedKey) || shownBoards[0];
  const selectedRun = selectedBoard ? own.get(selectedBoard.boardKey) : null;
  const conquered = shownBoards.filter((board) => own.has(board.boardKey)).length;
  const medals = shownBoards.filter((board) => Number(own.get(board.boardKey)?.place || 999) <= 3).length;
  const records = shownBoards.filter((board) => Number(own.get(board.boardKey)?.place || 999) === 1).length;
  return <div className="lab-stack"><section className="lab-band map-toolbar"><RunnerSearch players={players} value={runner} onChange={setRunner} label="Map for" /><div className="map-game-tabs">{games.map((item) => <button className={(games.includes(game) ? game : games[0]) === item ? 'active' : ''} key={item} onClick={() => { setGame(item); setSelectedKey(''); }}>{gameNames[item] || item}</button>)}</div></section><section className="lab-panel engine-map-panel"><div className="map-summary"><div><span>Conquered</span><strong>{conquered}/{shownBoards.length}</strong></div><div><span>Medals</span><strong>{medals}</strong></div><div><span>World records</span><strong>{records}</strong></div></div><div className="engine-map-grid">{shownBoards.map((board, index) => { const run = own.get(board.boardKey); const state = !run ? 'missing' : run.place === 1 ? 'wr' : run.place <= 3 ? 'medal' : 'ranked'; return <button className={`map-node ${state} ${selectedBoard?.boardKey === board.boardKey ? 'selected' : ''}`} key={board.boardKey} onClick={() => setSelectedKey(board.boardKey)}><span>{index + 1}</span><strong>{board.category}</strong><small>{[board.level, board.subcategory].filter(Boolean).join(' - ') || board.game}</small><em>{run ? `#${run.place}` : '?'}</em></button>; })}</div>{selectedBoard && <div className="map-detail"><span>{gameNames[selectedBoard.gameAbbr] || selectedBoard.gameAbbr}</span><strong>{insightBoardLabel(selectedBoard)}</strong><p>{selectedRun ? `${player.Runner} is #${selectedRun.place} of ${selectedRun.boardSize} with ${fmt(selectedRun.performancePoints, 2)} performance points.` : `${player.Runner} has not submitted to this ${selectedBoard.runCount}-runner board.`}</p></div>}</section></div>;
}

function Dynasties({ rows, openProfile }: { rows: InsightHistoryRow[]; openProfile: (runner: string) => void }) {
  const availableYears = useMemo(() => Array.from(new Set(rows.map((row) => Number(row.year || 0)).filter((year) => year >= 2015))).sort((a, b) => a - b), [rows]);
  const firstYear = availableYears[0] || 2015;
  const lastYear = availableYears.at(-1) || new Date().getUTCFullYear();
  const [range, setRange] = useState({ start: firstYear, end: lastYear });
  const start = Math.min(range.start, range.end);
  const end = Math.max(range.start, range.end);
  const years = availableYears.filter((year) => year >= start && year <= end);
  const careers = useMemo(() => dynastyTable(rows, start, end).slice(0, 35), [end, rows, start]);
  const champions = years.map((year) => rows.find((row) => Number(row.year) === year && Number(row.rank) === 1));
  const gridTemplate = `minmax(170px,1.3fr) repeat(${Math.max(1, years.length)}, minmax(62px,.55fr)) minmax(155px,1fr)`;
  return <div className="lab-stack">
    <section className="lab-band dynasty-toolbar"><div><span>Explore an era</span><strong>{start}–{end}</strong><small>Sorted by titles, then podiums, then top-10 seasons</small></div><label><span>From</span><select value={range.start} onChange={(event) => setRange((current) => ({ ...current, start: Number(event.target.value) }))}>{availableYears.map((year) => <option key={year}>{year}</option>)}</select></label><label><span>Through</span><select value={range.end} onChange={(event) => setRange((current) => ({ ...current, end: Number(event.target.value) }))}>{availableYears.map((year) => <option key={year}>{year}</option>)}</select></label></section>
    <section className="lab-panel dynasty-panel"><div className="lab-panel-title"><div><span>Dynasties</span><h3>Titles and staying power, year by year</h3></div><Crown size={22} /></div><p className="lab-explainer">There is no hidden career rating. Gold means yearly champion, silver and bronze mean podium finishes, and every cell states the runner&apos;s actual yearly rank. The percentage shows performance relative to that year&apos;s leader.</p>
      <div className="champion-belt">{champions.map((champion, index) => <button key={years[index]} disabled={!champion} onClick={() => champion && openProfile(champion.runner)}><span>{years[index]}</span><strong>{champion?.runner || 'No data'}</strong><small>{champion ? `${fmt(champion.performanceScore, 1)} performance` : '-'}</small></button>)}</div>
      <div className="dynasty-scroll"><div className="dynasty-matrix"><div className="dynasty-head" style={{ gridTemplateColumns: gridTemplate }}><span>Runner</span>{years.map((year) => <span key={year}>{year}</span>)}<span>Accomplishments</span></div>{careers.map((career, careerIndex) => <div className="dynasty-row" style={{ gridTemplateColumns: gridTemplate }} key={career.runner}><button className="dynasty-runner" onClick={() => openProfile(career.runner)}><span>{careerIndex + 1}</span><strong>{career.runner}<small>{career.appearances} active year{career.appearances === 1 ? '' : 's'}</small></strong></button>{years.map((year) => { const season = career.seasons.get(year); const state = !season ? 'empty' : season.rank === 1 ? 'title' : season.rank === 2 ? 'silver' : season.rank === 3 ? 'bronze' : season.rank <= 10 ? 'top10' : 'active'; return <button className={`dynasty-cell ${state}`} disabled={!season} title={season ? `${career.runner}: #${season.rank} in ${year}, ${fmt(season.leaderShare, 1)}% of the leader's performance` : `${career.runner}: no scored season in ${year}`} key={year}>{season ? <><strong>#{season.rank}</strong><small>{fmt(season.leaderShare)}%</small></> : <span>–</span>}</button>; })}<div className="dynasty-summary"><strong>{career.titles} title{career.titles === 1 ? '' : 's'}</strong><span>{career.podiums} podium{career.podiums === 1 ? '' : 's'} · {career.top10s} top-10{career.top10s === 1 ? '' : 's'}</span></div></div>)}</div></div>
    </section>
  </div>;
}

function EngineSeasons({ players, runs, openProfile }: { players: InsightPlayer[]; runs: InsightRun[]; openProfile: (runner: string) => void }) {
  const currentYear = new Date().getUTCFullYear();
  const years = useMemo(() => Array.from({ length: Math.max(1, currentYear - 2015 + 1) }, (_, index) => currentYear - index), [currentYear]);
  const [year, setYear] = useState(currentYear);
  const activeYear = years.includes(year) ? year : currentYear;
  const standings = useMemo(() => engineSeason(runs, players, activeYear).slice(0, 40), [activeYear, players, runs]);
  const rounds = useMemo(() => new Set(runs.filter((run) => String(run.runDate || '').startsWith(`${activeYear}-`)).map((run) => String(run.runDate).slice(0, 7))).size, [activeYear, runs]);
  const champion = standings[0];
  const mostWins = [...standings].sort((a, b) => b.wins - a.wins || b.points - a.points)[0];
  const ironRunner = [...standings].sort((a, b) => b.appearances - a.appearances || b.points - a.points)[0];
  return <div className="lab-stack"><section className="lab-band season-toolbar"><div><span>Engine season</span><strong>{activeYear}</strong><small>{rounds} monthly round{rounds === 1 ? '' : 's'} recorded</small></div><select value={activeYear} onChange={(event) => setYear(Number(event.target.value))}>{years.map((item) => <option value={item} key={item}>{item}</option>)}</select></section><div className="season-awards"><article><Trophy size={19} /><span>Championship leader</span><strong>{champion?.runner || '-'}</strong><small>{champion?.points || 0} points</small></article><article><Crown size={19} /><span>Most monthly wins</span><strong>{mostWins?.runner || '-'}</strong><small>{mostWins?.wins || 0} win{mostWins?.wins === 1 ? '' : 's'}</small></article><article><Gauge size={19} /><span>Most active months</span><strong>{ironRunner?.runner || '-'}</strong><small>{ironRunner?.appearances || 0} appearance{ironRunner?.appearances === 1 ? '' : 's'}</small></article></div><section className="lab-panel season-panel"><div className="lab-panel-title"><div><span>Every season from 2015</span><h3>{activeYear} monthly championship</h3></div><Trophy size={22} /></div><p className="lab-explainer">Current non-obsolete runs are grouped by their performed date. Each month is scored independently, then awards 25-18-15-12-10-8-6-4-2-1 championship points to its top ten.</p>{standings.length ? <div className="season-table">{standings.map((standing, index) => <button key={standing.runner} onClick={() => openProfile(standing.runner)}><span>{index + 1}</span><strong>{standing.runner}<small>{standing.appearances} active month{standing.appearances === 1 ? '' : 's'} · {standing.podiums} podium{standing.podiums === 1 ? '' : 's'}</small></strong><em>{standing.wins} win{standing.wins === 1 ? '' : 's'}</em><b>{standing.points}</b></button>)}</div> : <div className="season-empty"><CalendarDays size={24} /><strong>No dated runs in this season</strong><span>Try another year or include more games and categories.</span></div>}</section></div>;
}
