'use client';

import { useDeferredValue, useEffect, useMemo, useRef, useState } from 'react';
import { Activity, ArrowDown, ArrowUp, Award, CalendarRange, Check, ChevronDown, ChevronRight, ExternalLink, Filter, Flame, Gamepad2, GitBranch, Globe2, Info, ListFilter, Medal, Monitor, RotateCcw, Search, Settings2, SlidersHorizontal, Sparkles, Swords, TableProperties, Trophy, UserRound, X } from 'lucide-react';
import InsightsLab, { type LabMode } from './insights-lab';
import type { InsightCareerRun } from './insights';
import { buildExtremeRanks } from './extreme-ranks';
import RunnerInsights from './runner-insights';
import WrLineage from './wr-lineage';
import WorldView, { type RunnerMetadata, type WorldRun } from './world-view';
import UpdateFeed, { type ActivityData } from './update-feed';

type Player = { Rank: number; Runner: string; Country: string | null; 'Flag URL': string | null; 'Total Score': number; 'Performance Score': number; 'Volume Bonus': number; 'Variety Bonus': number; 'Prolific Score': number; 'Unique Boards': number; 'Unique Games': number; WRs: number; 'Top 3s': number; 'Top 10s': number; 'Medal Score': number; 'Depth Score': number; 'Average Place': number; Profile?: string; playerKey?: string; rawPerformance?: number };
type Run = { id: string; included: boolean; gameAbbr: string; game: string; scope: string; category: string; level: string | null; subcategory: string | null; place: number; boardSize: number; runner: string; country: string | null; time: string; seconds: number; platform: string | null; hardware: string | null; runDate: string | null; verifiedAt: string | null; runLink: string; playerKey: string; profile: string; performancePoints: number; medalPoints: number; depthPoints: number; wrCredit: number; top3Credit: number; top10Credit: number; boardKey: string; gameToggle: string };
type Board = { included: boolean; gameAbbr: string; game: string; scope: string; category: string; level: string | null; subcategory: string | null; runCount: number; timing: string; leaderboardLink: string; boardKey: string };
type Game = { included: boolean; abbr: string; name: string; id: string; leaderboardLink: string };
type HistoryRow = { month?: string; year?: number; rank: number; runner: string; country: string | null; totalScore: number; performanceScore: number; runs: number; volumeBonus: number; varietyBonus: number; uniqueBoards: number; uniqueGames: number; profile: string };
type WinnerRow = Record<string, string | number | null>;
type AboutRow = { Field: string; Details: string };
type SiteData = { generatedFrom: string; generatedAt: string; combined: Player[]; runs: Run[]; careerRuns?: InsightCareerRun[]; boards: Board[]; games: Game[]; monthly: HistoryRow[]; yearly: HistoryRow[]; monthlyWinners: WinnerRow[]; yearlyWinners: WinnerRow[]; about: AboutRow[] };
type View = 'leaderboard' | 'history' | 'lineage' | 'winners' | 'world' | 'runs' | 'lab';
type SortKey = 'Rank' | 'Total Score' | 'Performance Score' | 'Prolific Score' | 'Unique Boards' | 'WRs';
type ProfileTab = 'overview' | 'audit';

const PLAYER_BATCH_SIZE = 160;
const RUN_BATCH_SIZE = 240;
const views = new Set<View>(['leaderboard', 'history', 'lineage', 'winners', 'world', 'runs', 'lab']);
const sortKeys = new Set<SortKey>(['Rank', 'Total Score', 'Performance Score', 'Prolific Score', 'Unique Boards', 'WRs']);
const labModes = new Set<LabMode>(['simulator', 'milestones', 'momentum', 'timeline', 'map', 'hall', 'seasons']);

type RouteState = {
  view: View; extremeMode: boolean; query: string; country: string; sortKey: SortKey; descending: boolean;
  historyMode: 'monthly' | 'yearly'; historyPeriod: string; historyYear: string; winnerYear: string;
  runQuery: string; runGame: string; lineageGame: string; lineageBoard: string; labMode: LabMode; labRunner: string;
  profileRunner: string | null; profileTab: ProfileTab; compareOpen: boolean; runnerA: string; runnerB: string;
  performanceWeight: number; volumeCoefficient: number; varietyPerGame: number; density: 'comfortable' | 'compact'; showFlags: boolean; reduceMotion: boolean;
  worldQuery: string; worldGame: string; worldCountry: string; worldRegion: string;
  excludedGames: string[]; excludedBoards: string[];
};

function routeNumber(params: URLSearchParams, name: string, fallback: number, minimum: number, maximum: number) { const raw = params.get(name); if (raw === null || raw === '') return fallback; const value = Number(raw); return Number.isFinite(value) ? Math.max(minimum, Math.min(maximum, value)) : fallback; }

function readRouteState(): RouteState {
  if (typeof window === 'undefined') return { view: 'leaderboard', extremeMode: false, query: '', country: 'All countries', sortKey: 'Total Score', descending: true, historyMode: 'monthly', historyPeriod: '', historyYear: '', winnerYear: '', runQuery: '', runGame: 'All games', lineageGame: 'smb1', lineageBoard: '', labMode: 'simulator', labRunner: '', profileRunner: null, profileTab: 'overview', compareOpen: false, runnerA: 'Niftski', runnerB: '', performanceWeight: 1, volumeCoefficient: 8, varietyPerGame: 10, density: 'comfortable', showFlags: true, reduceMotion: false, worldQuery: '', worldGame: 'All games', worldCountry: '', worldRegion: '', excludedGames: [], excludedBoards: [] };
  const params = new URLSearchParams(window.location.search);
  const requestedView = params.get('view');
  const view = requestedView === 'extreme' ? 'leaderboard' : views.has(requestedView as View) ? requestedView as View : 'leaderboard';
  const requestedSort = params.get('sort') as SortKey;
  const requestedLabMode = params.get('labTool') as LabMode;
  return {
    view,
    extremeMode: requestedView === 'extreme' || params.get('extreme') === '1',
    query: params.get('q') || '', country: params.get('country') || 'All countries',
    sortKey: sortKeys.has(requestedSort) ? requestedSort : 'Total Score', descending: params.get('direction') !== 'asc',
    historyMode: params.get('historyMode') === 'yearly' ? 'yearly' : 'monthly', historyPeriod: params.get('period') || '', historyYear: params.get('historyYear') || '', winnerYear: params.get('winnerYear') || '',
    runQuery: params.get('runQuery') || '', runGame: params.get('runGame') || 'All games',
    lineageGame: params.get('lineageGame') || 'smb1', lineageBoard: params.get('lineageBoard') || '',
    labMode: labModes.has(requestedLabMode) ? requestedLabMode : 'simulator', labRunner: params.get('labRunner') || '',
    profileRunner: params.get('profile') || null, profileTab: params.get('profileTab') === 'audit' ? 'audit' : 'overview',
    compareOpen: params.get('compare') === '1', runnerA: params.get('runnerA') || 'Niftski', runnerB: params.get('runnerB') || '',
    performanceWeight: routeNumber(params, 'performanceWeight', 1, 0, 2), volumeCoefficient: routeNumber(params, 'volumeCoefficient', 8, 0, 20), varietyPerGame: routeNumber(params, 'varietyPerGame', 10, 0, 25),
    density: params.get('density') === 'compact' ? 'compact' : 'comfortable', showFlags: params.get('flags') !== '0', reduceMotion: params.get('motion') === 'reduced',
    worldQuery: params.get('worldQuery') || '', worldGame: params.get('worldGame') || 'All games', worldCountry: params.get('worldCountry') || '', worldRegion: params.get('worldRegion') || '',
    excludedGames: (params.get('excludeGames') || '').split(',').filter(Boolean), excludedBoards: (params.get('excludeBoards') || '').split(',').filter(Boolean),
  };
}

const columns: Array<{ key: SortKey; label: string }> = [
  { key: 'Total Score', label: 'Total' }, { key: 'Performance Score', label: 'Performance' },
  { key: 'Prolific Score', label: 'Runs' }, { key: 'Unique Boards', label: 'Boards' }, { key: 'WRs', label: 'WRs' },
];
const baseGameNames: Record<string, string> = { smb1: 'SMB1', smbce: 'SMB1 CE', smbtll: 'SMB2J', smbtllce: 'SMB2J CE', annsmb: 'ANN SMB', vssmb: 'VS. SMB' };
const countryCodes: Record<string, string> = {
  Albania:'al', Algeria:'dz', Antarctica:'aq', Argentina:'ar', Armenia:'am', Aruba:'aw', Australia:'au', Austria:'at',
  'Basque Country':'es/pv', Belarus:'by', Belgium:'be', Bolivia:'bo', 'Bosnia and Herzegovina':'ba', Brazil:'br',
  'British Indian Ocean Territory':'io', Bulgaria:'bg', Canada:'ca', Catalonia:'es/ct', Chad:'td', Chile:'cl', China:'cn',
  'Christmas Island':'cx', Colombia:'co', 'Costa Rica':'cr', Croatia:'hr', 'Czech Republic':'cz', Denmark:'dk',
  'Dominican Republic':'do', Ecuador:'ec', Egypt:'eg', 'El Salvador':'sv', England:'gb/eng', Esperanto:'eo',
  'European Union':'eu', Finland:'fi', France:'fr', 'French Polynesia':'pf', 'French Southern Territories':'tf', Germany:'de',
  Greece:'gr', Guam:'gu', Guatemala:'gt', 'Hong Kong':'hk', Hungary:'hu', Iceland:'is', India:'in', Indonesia:'id',
  Ireland:'ie', Israel:'il', Italy:'it', Japan:'jp', Jersey:'je', Jordan:'jo', Latvia:'lv', Lebanon:'lb', Lithuania:'lt',
  Macau:'mo', Malawi:'mw', Malaysia:'my', Malta:'mt', Mexico:'mx', Mongolia:'mn', Morocco:'ma', Netherlands:'nl',
  'New Zealand':'nz', Niger:'ne', 'North Korea':'kp', 'Northern Ireland':'gb/nir', Norway:'no', Palestine:'ps', Peru:'pe',
  Philippines:'ph', Poland:'pl', Portugal:'pt', 'Puerto Rico':'pr', 'Québec':'ca/qc', Romania:'ro', Russia:'ru',
  Scotland:'gb/sct', Serbia:'rs', Singapore:'sg', Slovenia:'si', 'South Africa':'za', 'South Korea':'kr', Spain:'es',
  Suriname:'sr', Sweden:'se', Switzerland:'ch', Taiwan:'tw', Thailand:'th', Turkey:'tr', Tuvalu:'tv', Uganda:'ug',
  Ukraine:'ua', 'United Arab Emirates':'ae', 'United Kingdom':'gb', 'United States':'us', Uruguay:'uy', Uzbekistan:'uz',
  Valhalla:'vh', 'Vatican City':'va', Venezuela:'ve', Vietnam:'vn', Wales:'gb/wls', Zimbabwe:'zw',
};

function number(value: number, decimals = 0) { return new Intl.NumberFormat('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals }).format(Number(value || 0)); }
function baseGame(toggle: string) { return toggle.replace(' (Luigi)', ''); }
function monthParts(value: string) { const match = /^(\d{4})-(\d{1,2})/.exec(value); return match ? { year: Number(match[1]), month: Number(match[2]) } : null; }
function monthSortValue(value: string) { const parts = monthParts(value); return parts ? parts.year * 100 + parts.month : 0; }
function monthLabel(value: string) { const parts = monthParts(value); return parts ? new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(Date.UTC(parts.year, parts.month - 1, 1))) : value; }
function monthName(value: string) { const parts = monthParts(value); return parts ? new Intl.DateTimeFormat('en-US', { month: 'long', timeZone: 'UTC' }).format(new Date(Date.UTC(parts.year, parts.month - 1, 1))) : value; }
function latestMonthlyPeriod(rows: HistoryRow[]) { return Array.from(new Set(rows.map((row) => row.month).filter((month): month is string => Boolean(month)))).sort((a, b) => monthSortValue(a) - monthSortValue(b)).at(-1) || ''; }
function latestWinnerYear(rows: WinnerRow[]) { const years = Array.from(new Set(rows.map((row) => monthParts(String(row.Month || ''))?.year).filter((year): year is number => Boolean(year)))).sort((a, b) => a - b); const currentYear = new Date().getUTCFullYear(); return String(years.includes(currentYear) ? currentYear : years.at(-1) || ''); }
function boardLabel(item: Pick<Run, 'category' | 'level' | 'subcategory'> | Pick<Board, 'category' | 'level' | 'subcategory'>) { return [item.category, item.level, item.subcategory].filter(Boolean).join(' · '); }
function countryFlagUrl(country: string | null) { const code = country ? countryCodes[country] : ''; return code ? `https://www.speedrun.com/images/flags/${code}.png` : null; }
function speedrunUrl(value: string | null | undefined) {
  if (!value) return null;
  try {
    const url = new URL(value);
    return url.protocol === 'https:' && (url.hostname === 'speedrun.com' || url.hostname.endsWith('.speedrun.com')) ? url.href : null;
  } catch {
    return null;
  }
}
function flagSource(value: string | null | undefined) {
  if (value && /^\.\/flags\/[a-z0-9-]+\.png$/i.test(value)) return value;
  return speedrunUrl(value);
}
function flagFor(player: { Runner?: string; runner?: string }, flags: Map<string, string | null>) { return flags.get(player.Runner || player.runner || '') || null; }
function Flag({ url }: { url: string | null }) {
  const src = flagSource(url);
  return src ? <FlagImage key={src} src={src} /> : <span className="flag flag-placeholder" />;
}
function FlagImage({ src }: { src: string }) {
  const [failed, setFailed] = useState(false);
  if (failed) return <span className="flag flag-placeholder" />;
  // Speedrun.com owns these tiny country assets; preserving their URLs keeps custom community flags intact.
  // eslint-disable-next-line @next/next/no-img-element
  return <img className="flag" src={src} alt="" loading="lazy" decoding="async" onError={() => setFailed(true)} />;
}
function AutoLoadMore({ hasMore, label, onLoadMore }: { hasMore: boolean; label: string; onLoadMore: () => void }) {
  const sentinel = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const node = sentinel.current;
    if (!node || !hasMore) return;
    let requested = false;
    const previous = node.previousElementSibling;
    const scrollContainer = previous instanceof HTMLElement && previous.classList.contains('table-scroll') ? previous : node.closest<HTMLElement>('.table-scroll');
    if (scrollContainer && scrollContainer.scrollHeight > scrollContainer.clientHeight + 2) {
      const onScroll = () => {
        if (!requested && scrollContainer.scrollHeight - scrollContainer.scrollTop - scrollContainer.clientHeight < 500) { requested = true; onLoadMore(); }
      };
      scrollContainer.addEventListener('scroll', onScroll, { passive: true });
      return () => scrollContainer.removeEventListener('scroll', onScroll);
    }
    const observer = new IntersectionObserver(([entry]) => { if (!requested && entry.isIntersecting) { requested = true; onLoadMore(); } }, { rootMargin: '500px 0px' });
    observer.observe(node);
    return () => observer.disconnect();
  }, [hasMore, onLoadMore]);
  return hasMore ? <div className="progress-loader" ref={sentinel}><span />{label}</div> : null;
}
function ScorePill({ label, value, tone = 'plain' }: { label: string; value: string; tone?: 'plain' | 'red' | 'blue' | 'green' }) { return <div className={`score-pill ${tone}`}><span>{label}</span><strong>{value}</strong></div>; }
function BrandLogo() {
  // The supplied pixel artwork is intentionally displayed without interpolation.
  // eslint-disable-next-line @next/next/no-img-element
  return <img src="./mario-logo.webp" alt="" />;
}

export default function Home() {
  const [data, setData] = useState<SiteData | null>(null);
  const [activityData, setActivityData] = useState<ActivityData | null>(null);
  const [runnerMetadata, setRunnerMetadata] = useState<RunnerMetadata[]>([]);
  const [routeReady, setRouteReady] = useState(false);
  const [view, setView] = useState<View>('leaderboard');
  const [extremeMode, setExtremeMode] = useState(false);
  const [query, setQuery] = useState(''); const [country, setCountry] = useState('All countries');
  const [sortKey, setSortKey] = useState<SortKey>('Total Score'); const [descending, setDescending] = useState(true);
  const [selectedGames, setSelectedGames] = useState<Set<string>>(new Set()); const [selectedBoards, setSelectedBoards] = useState<Set<string>>(new Set());
  const [filterOpen, setFilterOpen] = useState(false); const [boardQuery, setBoardQuery] = useState('');
  const [profileRunner, setProfileRunner] = useState<string | null>(null); const [profileTab, setProfileTab] = useState<ProfileTab>('overview');
  const [compareOpen, setCompareOpen] = useState(false); const [runnerA, setRunnerA] = useState('Niftski'); const [runnerB, setRunnerB] = useState('');
  const [runnerASearch, setRunnerASearch] = useState(''); const [runnerBSearch, setRunnerBSearch] = useState('');
  const [settingsOpen, setSettingsOpen] = useState(false); const [settingsSection, setSettingsSection] = useState<'runner' | 'scoring' | 'display' | 'about'>('runner'); const [updateOpen, setUpdateOpen] = useState(false); const [historyMode, setHistoryMode] = useState<'monthly' | 'yearly'>('monthly');
  const [historyPeriod, setHistoryPeriod] = useState(''); const [historyYear, setHistoryYear] = useState(''); const [runQuery, setRunQuery] = useState(''); const [runGame, setRunGame] = useState('All games');
  const [winnerYear, setWinnerYear] = useState('');
  const [lineageGame, setLineageGame] = useState('smb1'); const [lineageBoard, setLineageBoard] = useState('');
  const [labMode, setLabMode] = useState<LabMode>('simulator'); const [labRunner, setLabRunner] = useState('');
  const [performanceWeight, setPerformanceWeight] = useState(1); const [volumeCoefficient, setVolumeCoefficient] = useState(8); const [varietyPerGame, setVarietyPerGame] = useState(10);
  const [density, setDensity] = useState<'comfortable' | 'compact'>('comfortable'); const [showFlags, setShowFlags] = useState(true); const [reduceMotion, setReduceMotion] = useState(false);
  const [myRunner, setMyRunner] = useState(''); const [myRunnerSearch, setMyRunnerSearch] = useState(''); const [preferencesReady, setPreferencesReady] = useState(false);
  const [worldQuery, setWorldQuery] = useState(''); const [worldGame, setWorldGame] = useState('All games'); const [worldCountry, setWorldCountry] = useState(''); const [worldRegion, setWorldRegion] = useState('');
  const [playerPaging, setPlayerPaging] = useState({ key: '', limit: PLAYER_BATCH_SIZE }); const [runPaging, setRunPaging] = useState({ key: '', limit: RUN_BATCH_SIZE });
  const deferredQuery = useDeferredValue(query); const deferredRunQuery = useDeferredValue(runQuery);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    setMyRunner(window.localStorage.getItem('smb1ecl.myRunner') || '');
    setPreferencesReady(true);
  }, []);
  useEffect(() => {
    if (!preferencesReady || typeof window === 'undefined') return;
    if (myRunner) window.localStorage.setItem('smb1ecl.myRunner', myRunner);
    else window.localStorage.removeItem('smb1ecl.myRunner');
  }, [myRunner, preferencesReady]);

  useEffect(() => {
    const route = readRouteState();
    setView(route.view); setExtremeMode(route.extremeMode); setQuery(route.query); setCountry(route.country); setSortKey(route.sortKey); setDescending(route.descending);
    setHistoryMode(route.historyMode); setRunQuery(route.runQuery); setRunGame(route.runGame); setLineageGame(route.lineageGame); setLineageBoard(route.lineageBoard); setLabMode(route.labMode); setLabRunner(route.labRunner);
    setProfileRunner(route.profileRunner); setProfileTab(route.profileTab); setCompareOpen(route.compareOpen); setRunnerA(route.runnerA); setRunnerB(route.runnerB);
    setPerformanceWeight(route.performanceWeight); setVolumeCoefficient(route.volumeCoefficient); setVarietyPerGame(route.varietyPerGame); setDensity(route.density); setShowFlags(route.showFlags); setReduceMotion(route.reduceMotion);
    setWorldQuery(route.worldQuery); setWorldGame(route.worldGame); setWorldCountry(route.worldCountry); setWorldRegion(route.worldRegion);
    setRouteReady(true);
    const version = Date.now();
    fetch(`./activity.json?v=${version}`, { cache: 'no-store' }).then((response) => response.ok ? response.json() : null).then((payload: ActivityData | null) => setActivityData(payload)).catch(() => setActivityData(null));
    fetch(`./runner-metadata.json?v=${version}`, { cache: 'no-store' }).then((response) => response.ok ? response.json() : { players: [] }).then((payload: unknown) => setRunnerMetadata((payload as { players?: RunnerMetadata[] }).players || [])).catch(() => setRunnerMetadata([]));
    fetch(`./data/site-data-manifest.json?v=${version}`, { cache: 'no-store' })
      .then((response) => response.json())
      .then((value) => { const manifest = value as { parts: string[] }; return Promise.all(manifest.parts.map((part) => fetch(`./data/${part}?v=${version}`, { cache: 'no-store' }).then((response) => response.text()))); })
      .then((parts) => JSON.parse(parts.join('')) as SiteData)
      .then((payload) => {
        const latestMonth = latestMonthlyPeriod(payload.monthly);
        const excludedGames = new Set(route.excludedGames); const excludedBoards = new Set(route.excludedBoards);
        const monthlyPeriods = new Set(payload.monthly.map((row) => row.month).filter(Boolean)); const yearlyPeriods = new Set(payload.yearly.map((row) => String(row.year)));
        const requestedHistoryPeriod = route.historyMode === 'monthly' ? (monthlyPeriods.has(route.historyPeriod) ? route.historyPeriod : latestMonth) : (yearlyPeriods.has(route.historyPeriod) ? route.historyPeriod : Array.from(yearlyPeriods).sort().at(-1) || '');
        const requestedWinnerYear = Array.from(new Set(payload.monthlyWinners.map((row) => String(monthParts(String(row.Month || ''))?.year || '')))).includes(route.winnerYear) ? route.winnerYear : latestWinnerYear(payload.monthlyWinners);
        setData(payload);
        setSelectedGames(new Set(payload.games.filter((game) => game.included && !excludedGames.has(game.abbr)).map((game) => game.abbr)));
        setSelectedBoards(new Set(payload.boards.filter((board) => board.included && !excludedBoards.has(board.boardKey)).map((board) => board.boardKey)));
        if (!route.runnerB) setRunnerB(payload.combined[1]?.Runner || '');
        setHistoryPeriod(requestedHistoryPeriod); setHistoryYear(route.historyMode === 'monthly' ? route.historyYear || String(monthParts(requestedHistoryPeriod)?.year || '') : ''); setWinnerYear(requestedWinnerYear);
      });
  }, []);
  useEffect(() => {
    if (!routeReady || !data || typeof window === 'undefined') return;
    const url = new URL(window.location.href);
    const params = url.searchParams;
    ['view', 'extreme', 'q', 'country', 'sort', 'direction', 'historyMode', 'period', 'historyYear', 'winnerYear', 'runQuery', 'runGame', 'lineageGame', 'lineageBoard', 'labTool', 'labRunner', 'profile', 'profileTab', 'compare', 'runnerA', 'runnerB', 'excludeGames', 'excludeBoards', 'performanceWeight', 'volumeCoefficient', 'varietyPerGame', 'density', 'flags', 'motion', 'worldQuery', 'worldGame', 'worldCountry', 'worldRegion'].forEach((key) => params.delete(key));
    if (view !== 'leaderboard') params.set('view', view);
    if (view === 'leaderboard') { if (extremeMode) params.set('extreme', '1'); if (query) params.set('q', query); if (country !== 'All countries') params.set('country', country); if (sortKey !== 'Total Score') params.set('sort', sortKey); if (!descending) params.set('direction', 'asc'); }
    if (view === 'history') { if (historyMode !== 'monthly') params.set('historyMode', historyMode); if (historyPeriod) params.set('period', historyPeriod); if (historyMode === 'monthly' && historyYear) params.set('historyYear', historyYear); }
    if (view === 'winners' && winnerYear) params.set('winnerYear', winnerYear);
    if (view === 'runs') { if (runQuery) params.set('runQuery', runQuery); if (runGame !== 'All games') params.set('runGame', runGame); }
    if (view === 'lineage') { if (lineageGame !== 'smb1') params.set('lineageGame', lineageGame); if (lineageBoard) params.set('lineageBoard', lineageBoard); }
    if (view === 'lab') { if (labMode !== 'simulator') params.set('labTool', labMode); if (labRunner) params.set('labRunner', labRunner); }
    if (view === 'world') { if (worldQuery) params.set('worldQuery', worldQuery); if (worldGame !== 'All games') params.set('worldGame', worldGame); if (worldCountry) params.set('worldCountry', worldCountry); if (worldRegion) params.set('worldRegion', worldRegion); }
    if (performanceWeight !== 1) params.set('performanceWeight', String(performanceWeight)); if (volumeCoefficient !== 8) params.set('volumeCoefficient', String(volumeCoefficient)); if (varietyPerGame !== 10) params.set('varietyPerGame', String(varietyPerGame));
    if (density === 'compact') params.set('density', density); if (!showFlags) params.set('flags', '0'); if (reduceMotion) params.set('motion', 'reduced');
    if (profileRunner) params.set('profile', profileRunner); if (profileRunner && profileTab !== 'overview') params.set('profileTab', profileTab);
    if (view === 'leaderboard' && compareOpen) { params.set('compare', '1'); if (runnerA !== 'Niftski') params.set('runnerA', runnerA); if (runnerB) params.set('runnerB', runnerB); }
    const defaultGames = new Set(data.games.filter((game) => game.included).map((game) => game.abbr)); const defaultBoards = new Set(data.boards.filter((board) => board.included).map((board) => board.boardKey));
    const excludedGames = Array.from(defaultGames).filter((game) => !selectedGames.has(game)); const excludedBoards = Array.from(defaultBoards).filter((board) => !selectedBoards.has(board));
    if (excludedGames.length) params.set('excludeGames', excludedGames.join(',')); if (excludedBoards.length) params.set('excludeBoards', excludedBoards.join(','));
    window.history.replaceState(null, '', `${url.pathname}${params.size ? `?${params.toString()}` : ''}${url.hash}`);
  }, [compareOpen, country, data, density, descending, extremeMode, historyMode, historyPeriod, historyYear, labMode, labRunner, lineageBoard, lineageGame, performanceWeight, profileRunner, profileTab, query, reduceMotion, routeReady, runGame, runQuery, runnerA, runnerB, selectedBoards, selectedGames, showFlags, sortKey, varietyPerGame, view, volumeCoefficient, winnerYear, worldCountry, worldGame, worldQuery, worldRegion]);
  useEffect(() => { function onKey(event: KeyboardEvent) { if (event.key === '/' && !['INPUT', 'SELECT', 'TEXTAREA'].includes((event.target as HTMLElement).tagName)) { event.preventDefault(); document.querySelector<HTMLInputElement>('#runner-search')?.focus(); } if (event.key === 'Escape') { setFilterOpen(false); setProfileRunner(null); setCompareOpen(false); setSettingsOpen(false); setUpdateOpen(false); } } window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: 'auto' }); }, [view]);
  useEffect(() => {
    if (!data || !myRunner) return;
    const canonical = data.combined.find((player) => String(player.Runner).toLocaleLowerCase() === myRunner.toLocaleLowerCase())?.Runner;
    if (canonical && canonical !== myRunner) setMyRunner(String(canonical));
  }, [data, myRunner]);

  const flags = useMemo(() => new Map(data?.combined.map((player) => [String(player.Runner), player['Flag URL'] || countryFlagUrl(player.Country)]) || []), [data]);
  const filteredRuns = useMemo(() => data?.runs.filter((run) => run.included && selectedGames.has(run.gameToggle) && selectedBoards.has(run.boardKey)) || [], [data, selectedBoards, selectedGames]);
  const filteredCareerRuns = useMemo(() => { const source = data?.careerRuns?.length ? data.careerRuns : data?.runs || []; return source.filter((run) => selectedGames.has(run.gameToggle) && selectedBoards.has(run.boardKey)); }, [data, selectedBoards, selectedGames]);
  const extremeLeaderboard = useMemo<{ players: Player[]; runs: Run[] }>(() => {
    if (!data) return { players: [], runs: [] };
    const result = buildExtremeRanks(filteredCareerRuns, data.combined);
    const weighted = result.players.map((player) => {
      const performance = Number(player['Performance Score'] || 0) * performanceWeight; const volume = Math.sqrt(Number(player['Prolific Score'] || 0)) * volumeCoefficient; const variety = Math.max(0, Number(player['Unique Games'] || 0) - 1) * varietyPerGame;
      return { ...player, rawPerformance: Number(player['Performance Score'] || 0), 'Performance Score': performance, 'Volume Bonus': volume, 'Variety Bonus': variety, 'Total Score': performance + volume + variety, 'Flag URL': player['Flag URL'] || countryFlagUrl(player.Country) } as Player;
    }).sort((a, b) => b['Total Score'] - a['Total Score'] || b['Performance Score'] - a['Performance Score'] || String(a.Runner).localeCompare(String(b.Runner))).map((player, index) => ({ ...player, Rank: index + 1 }));
    return {
      players: weighted,
      runs: result.runs,
    };
  }, [data, filteredCareerRuns, performanceWeight, varietyPerGame, volumeCoefficient]);
  const extremeBoardCounts = useMemo(() => (data?.careerRuns || []).reduce((counts, run) => counts.set(run.boardKey, (counts.get(run.boardKey) || 0) + 1), new Map<string, number>()), [data]);
  const insightBoards = useMemo(() => data?.boards.filter((board) => { const toggle = board.subcategory?.includes('Luigi') ? `${board.gameAbbr} (Luigi)` : board.gameAbbr; return selectedBoards.has(board.boardKey) && selectedGames.has(toggle); }) || [], [data, selectedBoards, selectedGames]);
  const scoredPlayers = useMemo(() => {
    if (!data) return [];
    const combinedByName = new Map(data.combined.map((player) => [String(player.Runner), player]));
    const groups = new Map<string, { runner: string; country: string | null; profile: string; performance: number; runs: number; boards: Set<string>; games: Set<string>; wr: number; top3: number; top10: number; medal: number; depth: number; places: number[] }>();
    filteredRuns.forEach((run) => { const runnerName = String(run.runner || 'Unknown runner'); const current = groups.get(run.playerKey) || { runner: runnerName, country: run.country, profile: run.profile, performance: 0, runs: 0, boards: new Set<string>(), games: new Set<string>(), wr: 0, top3: 0, top10: 0, medal: 0, depth: 0, places: [] }; current.performance += Number(run.performancePoints || 0); current.runs += 1; current.boards.add(run.boardKey); current.games.add(baseGame(run.gameToggle)); current.wr += Number(run.wrCredit || 0); current.top3 += Number(run.top3Credit || 0); current.top10 += Number(run.top10Credit || 0); current.medal += Number(run.medalPoints || 0); current.depth += Number(run.depthPoints || 0); current.places.push(Number(run.place || 0)); groups.set(run.playerKey, current); });
    const result = Array.from(groups.entries()).map(([playerKey, group]) => { const performance = group.performance * performanceWeight; const volume = Math.sqrt(group.runs) * volumeCoefficient; const variety = Math.max(0, group.games.size - 1) * varietyPerGame; const source = combinedByName.get(group.runner); return { Rank: 0, Runner: group.runner, Country: group.country, 'Flag URL': source?.['Flag URL'] || countryFlagUrl(group.country), 'Total Score': performance + volume + variety, 'Performance Score': performance, 'Volume Bonus': volume, 'Variety Bonus': variety, 'Prolific Score': group.runs, 'Unique Boards': group.boards.size, 'Unique Games': group.games.size, WRs: group.wr, 'Top 3s': group.top3, 'Top 10s': group.top10, 'Medal Score': group.medal, 'Depth Score': group.depth, 'Average Place': group.places.reduce((sum, place) => sum + place, 0) / group.places.length, Profile: group.profile, playerKey, rawPerformance: group.performance } as Player; }).sort((a, b) => b['Total Score'] - a['Total Score'] || b['Performance Score'] - a['Performance Score'] || String(a.Runner).localeCompare(String(b.Runner)));
    return result.map((player, index) => ({ ...player, Rank: index + 1 }));
  }, [data, filteredRuns, performanceWeight, varietyPerGame, volumeCoefficient]);
  const officialScoredPlayers = useMemo(() => scoredPlayers.map((player) => { const performance = Number(player.rawPerformance || 0); const volume = Math.sqrt(Number(player['Prolific Score'] || 0)) * 8; const variety = Math.max(0, Number(player['Unique Games'] || 0) - 1) * 10; return { ...player, 'Performance Score': performance, 'Volume Bonus': volume, 'Variety Bonus': variety, 'Total Score': performance + volume + variety }; }).sort((a, b) => b['Total Score'] - a['Total Score'] || b['Performance Score'] - a['Performance Score'] || String(a.Runner).localeCompare(String(b.Runner))).map((player, index) => ({ ...player, Rank: index + 1 })), [scoredPlayers]);
  const customScoring = performanceWeight !== 1 || volumeCoefficient !== 8 || varietyPerGame !== 10;
  const leaderboardPlayers = extremeMode ? extremeLeaderboard.players : scoredPlayers;
  const myPlayer = useMemo(() => leaderboardPlayers.find((player) => player.Runner === myRunner) || null, [leaderboardPlayers, myRunner]);
  const myBasePlayer = useMemo(() => data?.combined.find((player) => player.Runner === myRunner) || null, [data, myRunner]);
  const myPlayerIndex = myPlayer ? leaderboardPlayers.findIndex((player) => player.Runner === myRunner) : -1;
  const runnerAhead = myPlayerIndex > 0 ? leaderboardPlayers[myPlayerIndex - 1] : null;
  const runnerBehind = myPlayerIndex >= 0 && myPlayerIndex < leaderboardPlayers.length - 1 ? leaderboardPlayers[myPlayerIndex + 1] : null;
  const latestChangeCount = activityData?.status === 'ready' ? activityData.summary.newRuns + activityData.summary.newRunners + activityData.summary.rankMovers + activityData.summary.newWrs : 0;
  const countries = useMemo(() => Array.from(new Set(leaderboardPlayers.map((player) => player.Country).filter(Boolean))).sort() as string[], [leaderboardPlayers]);
  const matchingPlayers = useMemo(() => { const needle = deferredQuery.trim().toLocaleLowerCase(); return leaderboardPlayers.filter((player) => (!needle || String(player.Runner).toLocaleLowerCase().includes(needle)) && (country === 'All countries' || player.Country === country)).sort((a, b) => { const direction = descending ? -1 : 1; return direction * (Number(a[sortKey] || 0) - Number(b[sortKey] || 0)) || String(a.Runner).localeCompare(String(b.Runner)); }); }, [country, deferredQuery, descending, leaderboardPlayers, sortKey]);
  const playerPageKey = `${extremeMode}|${deferredQuery}|${country}|${sortKey}|${descending}|${Array.from(selectedGames).sort().join(',')}|${Array.from(selectedBoards).sort().join(',')}`;
  const playerLimit = playerPaging.key === playerPageKey ? playerPaging.limit : PLAYER_BATCH_SIZE;
  const visiblePlayers = matchingPlayers.slice(0, playerLimit);
  const profileMode = extremeMode ? 'extreme' : 'current';
  const selectedPlayer = useMemo(() => leaderboardPlayers.find((player) => player.Runner === profileRunner) || null, [leaderboardPlayers, profileRunner]);
  const selectedPlayerRuns = useMemo(() => (profileMode === 'extreme' ? extremeLeaderboard.runs : filteredRuns).filter((run) => run.runner === profileRunner).map((run) => ({ ...run, performancePoints: run.performancePoints * performanceWeight })).sort((a, b) => b.performancePoints - a.performancePoints), [extremeLeaderboard.runs, filteredRuns, performanceWeight, profileMode, profileRunner]);
  const boardGroups = useMemo(() => { if (!data) return []; const needle = boardQuery.trim().toLocaleLowerCase(); return data.games.map((game) => ({ game, boards: data.boards.filter((board) => board.gameAbbr === baseGame(game.abbr) && (game.abbr.includes('Luigi') ? board.subcategory?.includes('Luigi') : !board.subcategory?.includes('Luigi')) && (!needle || `${board.game} ${boardLabel(board)}`.toLocaleLowerCase().includes(needle))) })).filter((group) => group.boards.length); }, [boardQuery, data]);
  const comparison = useMemo(() => { const a = new Map(filteredRuns.filter((run) => run.runner === runnerA).map((run) => [run.boardKey, run])); const b = new Map(filteredRuns.filter((run) => run.runner === runnerB).map((run) => [run.boardKey, run])); return Array.from(a.entries()).filter(([key]) => b.has(key)).map(([, runA]) => { const runB = b.get(runA.boardKey)!; const leader = runA.place < runB.place ? runnerA : runB.place < runA.place ? runnerB : runA.seconds < runB.seconds ? runnerA : runB.seconds < runA.seconds ? runnerB : 'Tie'; return { runA, runB, leader }; }).sort((x, y) => Math.min(x.runA.place, x.runB.place) - Math.min(y.runA.place, y.runB.place)); }, [filteredRuns, runnerA, runnerB]);
  const historyYears = useMemo(() => Array.from(new Set((data?.monthly || []).map((row) => String(monthParts(String(row.month || ''))?.year || '')).filter(Boolean))).sort((a, b) => Number(b) - Number(a)), [data]);
  const historyPeriods = useMemo(() => { if (!data) return []; return historyMode === 'monthly' ? Array.from(new Set(data.monthly.map((row) => row.month!).filter((period) => String(monthParts(period)?.year || '') === historyYear))).sort((a, b) => monthSortValue(b) - monthSortValue(a)) : Array.from(new Set(data.yearly.map((row) => String(row.year)))).sort().reverse(); }, [data, historyMode, historyYear]);
  const historyRows = useMemo(() => { if (!data) return []; return (historyMode === 'monthly' ? data.monthly.filter((row) => row.month === historyPeriod) : data.yearly.filter((row) => String(row.year) === historyPeriod)).sort((a, b) => a.rank - b.rank); }, [data, historyMode, historyPeriod]);
  const winnerYears = useMemo(() => Array.from(new Set((data?.monthlyWinners || []).map((row) => String(monthParts(String(row.Month || ''))?.year || '')).filter(Boolean))).sort((a, b) => Number(b) - Number(a)), [data]);
  const monthlyChampions = useMemo(() => [...(data?.monthlyWinners || [])].filter((row) => String(monthParts(String(row.Month || ''))?.year || '') === winnerYear).sort((a, b) => monthSortValue(String(b.Month || '')) - monthSortValue(String(a.Month || ''))), [data, winnerYear]);
  const matchingRuns = useMemo(() => { if (!data) return []; const needle = deferredRunQuery.trim().toLocaleLowerCase(); return data.runs.filter((run) => (runGame === 'All games' || run.gameToggle === runGame) && (!needle || `${run.runner} ${run.game} ${boardLabel(run)}`.toLocaleLowerCase().includes(needle))).sort((a, b) => b.performancePoints - a.performancePoints); }, [data, deferredRunQuery, runGame]);
  const runPageKey = `${deferredRunQuery}|${runGame}`;
  const runLimit = runPaging.key === runPageKey ? runPaging.limit : RUN_BATCH_SIZE;
  const visibleRuns = matchingRuns.slice(0, runLimit);
  const freshness = useMemo(() => {
    if (!data?.generatedAt) return { label: 'Loading data', title: 'Loading the latest published snapshot.' };
    const built = new Date(data.generatedAt);
    const latestVerified = data.runs.reduce<string | null>((latest, run) => !run.verifiedAt || (latest && run.verifiedAt <= latest) ? latest : run.verifiedAt, null);
    const format = (date: Date, includeTime = false) => date.toLocaleString('en-US', { month: 'short', day: 'numeric', ...(includeTime ? { hour: '2-digit', minute: '2-digit', hour12: false } : {}), timeZone: 'UTC', timeZoneName: includeTime ? 'short' : undefined });
    return { label: `Updated ${format(built)}`, title: `Site rebuilt ${format(built, true)}.${latestVerified ? ` Newest verification: ${format(new Date(latestVerified), true)}.` : ''}` };
  }, [data]);

  function setPlayerLimit(update: (current: number) => number) { setPlayerPaging((current) => ({ key: playerPageKey, limit: update(current.key === playerPageKey ? current.limit : PLAYER_BATCH_SIZE) })); }
  function setRunLimit(update: (current: number) => number) { setRunPaging((current) => ({ key: runPageKey, limit: update(current.key === runPageKey ? current.limit : RUN_BATCH_SIZE) })); }
  function selectHistoryYear(year: string) { const periods = Array.from(new Set((data?.monthly || []).map((row) => row.month!).filter((period) => String(monthParts(period)?.year || '') === year))).sort((a, b) => monthSortValue(a) - monthSortValue(b)); setHistoryYear(year); setHistoryPeriod(periods.at(-1) || ''); }
  function changeSort(key: SortKey) { if (sortKey === key) setDescending((value) => !value); else { setSortKey(key); setDescending(key !== 'Rank'); } }
  function toggleGame(game: string) { setSelectedGames((current) => { const next = new Set(current); if (next.has(game)) next.delete(game); else next.add(game); return next; }); }
  function toggleLuigi() { const luigi = data?.games.filter((game) => game.abbr.includes('Luigi')).map((game) => game.abbr) || []; const allOn = luigi.every((game) => selectedGames.has(game)); setSelectedGames((current) => { const next = new Set(current); luigi.forEach((game) => allOn ? next.delete(game) : next.add(game)); return next; }); }
  function toggleBoard(key: string) { setSelectedBoards((current) => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next; }); }
  function resetFilters() { if (!data) return; setSelectedGames(new Set(data.games.filter((game) => game.included).map((game) => game.abbr))); setSelectedBoards(new Set(data.boards.filter((board) => board.included).map((board) => board.boardKey))); }
  function openProfile(runner: string, tab: ProfileTab = 'overview') { setProfileRunner(runner); setProfileTab(tab); }
  function navigate(nextView: View) { if (nextView === 'lab' && myRunner && !labRunner) setLabRunner(myRunner); setView(nextView); }
  function openComparison(opponent = '') { if (myRunner) setRunnerA(myRunner); if (opponent) setRunnerB(opponent); setCompareOpen(true); }
  const luigiSelected = data?.games.filter((game) => game.abbr.includes('Luigi')).every((game) => selectedGames.has(game.abbr)) ?? false;
  const activeFilterCount = (data?.games.length || 0) - selectedGames.size + (data?.boards.length || 0) - selectedBoards.size;

  return <main className={`app-shell density-${density} ${showFlags ? '' : 'hide-flags'} ${reduceMotion ? 'reduce-motion' : ''}`}>
    <header className="topbar"><button className="brand-lockup" onClick={() => navigate('leaderboard')}><span className="brand-mark"><BrandLogo /></span><span><span className="brand-kicker">SMB1 Engine</span><strong>Combined Leaderboard</strong></span></button><nav className="primary-nav" aria-label="Primary navigation">{([{ view: 'leaderboard', label: 'Ranks', mobileLabel: 'Ranks', Icon: Medal }, { view: 'history', label: 'History', mobileLabel: 'History', Icon: CalendarRange }, { view: 'winners', label: 'Winners', mobileLabel: 'Winners', Icon: Trophy }, { view: 'lineage', label: 'WR Lineage', mobileLabel: 'Lineage', Icon: GitBranch }, { view: 'world', label: 'World', mobileLabel: 'World', Icon: Globe2 }, { view: 'runs', label: 'Runs', mobileLabel: 'Runs', Icon: TableProperties }, { view: 'lab', label: 'Lab', mobileLabel: 'Lab', Icon: Sparkles }] as const).map(({ view: item, label, mobileLabel, Icon }) => <button key={item} className={`nav-item ${view === item ? 'active' : ''}`} aria-current={view === item ? 'page' : undefined} onClick={() => navigate(item)}><Icon size={18} /><span className="desktop-nav-label">{label}</span><span className="mobile-nav-label">{mobileLabel}</span></button>)}</nav><div className="topbar-actions"><button className="freshness freshness-button" title={`${freshness.title} Open latest update.`} onClick={() => setUpdateOpen(true)}><span /> {freshness.label}</button><button className="icon-button update-button" onClick={() => setUpdateOpen(true)} aria-label="Latest leaderboard update" title="Latest leaderboard update"><Activity size={18} />{latestChangeCount > 0 && <span className="update-badge" aria-hidden="true">{Math.min(99, latestChangeCount)}</span>}</button><button className={`icon-button ${customScoring ? 'settings-active' : ''}`} onClick={() => setSettingsOpen(true)} title="Settings and about"><Settings2 size={18} /></button></div></header>
    <section className="content">
      {view === 'leaderboard' && <>
        <div className="page-heading leaderboard-heading"><div><p className={`eyebrow ${extremeMode ? 'extreme-eyebrow' : ''}`}>{extremeMode ? 'Every accepted submission since 2015' : 'All current non-obsolete runs'}</p><h2>Leaderboard</h2></div><div className="leaderboard-heading-actions">{customScoring && <button className="custom-scoring-badge" onClick={() => { setSettingsSection('scoring'); setSettingsOpen(true); }}><SlidersHorizontal size={14} />Custom scoring</button>}<label className={`extreme-mode-toggle ${extremeMode ? 'active' : ''}`}><input type="checkbox" checked={extremeMode} onChange={(event) => setExtremeMode(event.target.checked)} /><Flame size={16} /><span><strong>Extreme mode</strong><small>Count every accepted run</small></span></label>{!extremeMode && <button className="compare-button" aria-label="Open head-to-head comparison" title="Head-to-head" onClick={() => openComparison()}><Swords size={17} /> Head-to-head</button>}</div></div>
        <div className={`snapshot-bar ${extremeMode ? 'extreme-snapshot' : ''}`}><div><Gamepad2 size={19} /><strong>{selectedGames.size}</strong><span>Groups included</span></div><div><TableProperties size={18} /><strong>{number(selectedBoards.size)}</strong><span>Boards included</span></div><div>{extremeMode ? <Flame size={18} /> : <Activity size={18} />}<strong>{number(extremeMode ? filteredCareerRuns.length : filteredRuns.length)}</strong><span>{extremeMode ? 'Accepted runs' : 'Current runs'}</span></div><div><UserRound size={18} /><strong>{number(leaderboardPlayers.length)}</strong><span>Ranked runners</span></div><p>{extremeMode ? 'Obsolete and superseded submissions count individually. Times are reranked inside the complete accepted-run archive.' : 'Every toggle rebuilds performance, volume, variety and total score from the included runs.'}</p></div>
        <div className="game-strip"><span>Games</span>{Object.entries(baseGameNames).map(([game, label]) => <button className={`game-chip ${selectedGames.has(game) ? 'selected' : ''}`} onClick={() => toggleGame(game)} key={game}>{selectedGames.has(game) && <Check size={12} />}{label}</button>)}<button className={`game-chip luigi ${luigiSelected ? 'selected' : ''}`} onClick={toggleLuigi}>{luigiSelected && <Check size={12} />}Luigi boards</button></div>
        {myRunner && <section className="my-runner-bar">{myPlayer ? <><button className="my-runner-identity" onClick={() => openProfile(myRunner)}><Flag url={myPlayer['Flag URL']} /><span><small>MY RUNNER</small><strong>{myRunner}</strong></span><b>#{myPlayer.Rank}</b></button><div><span>Total score</span><strong>{number(myPlayer['Total Score'], 2)}</strong></div><div><span>{runnerAhead ? `To #${runnerAhead.Rank} ${runnerAhead.Runner}` : 'Current position'}</span><strong>{runnerAhead ? `${number(Math.max(0, runnerAhead['Total Score'] - myPlayer['Total Score'] + .01), 2)} pts` : 'Engine leader'}</strong></div><div className="my-runner-behind"><span>{runnerBehind ? `Lead over #${runnerBehind.Rank}` : 'Current runs'}</span><strong>{runnerBehind ? `${number(myPlayer['Total Score'] - runnerBehind['Total Score'], 2)} pts` : number(myPlayer['Prolific Score'])}</strong></div><button className="my-runner-action" onClick={() => openComparison(runnerAhead?.Runner || runnerBehind?.Runner || '')}><Swords size={15} /> Chase</button></> : <><div className="my-runner-filtered"><UserRound size={18} /><span><strong>{myRunner}</strong><small>Not ranked under the current category filters.</small></span></div><button className="my-runner-action" onClick={() => resetFilters()}><RotateCcw size={15} /> Reset filters</button></>}</section>}
        <section className={`leaderboard-surface ${extremeMode ? 'extreme-surface' : ''}`}><div className="table-toolbar"><label className="search-box"><Search size={17} /><input id="runner-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${number(leaderboardPlayers.length)} runners`} /><kbd>/</kbd></label><div className="mobile-sort"><select aria-label={`Sort ${extremeMode ? 'Extreme Mode' : 'leaderboard'}`} value={sortKey} onChange={(event) => { const key = event.target.value as SortKey; setSortKey(key); setDescending(key !== 'Rank'); }}><option value="Rank">Rank</option>{columns.map((column) => <option value={column.key} key={column.key}>{column.label}</option>)}</select><button className="icon-button" aria-label={descending ? 'Sort ascending' : 'Sort descending'} title={descending ? 'Sort ascending' : 'Sort descending'} onClick={() => setDescending((value) => !value)}>{descending ? <ArrowDown size={16} /> : <ArrowUp size={16} />}</button></div><select aria-label={`Filter ${extremeMode ? 'Extreme Mode' : 'leaderboard'} by country`} value={country} onChange={(event) => setCountry(event.target.value)}><option>All countries</option>{countries.map((item) => <option key={item}>{item}</option>)}</select><button className={`filter-button ${activeFilterCount ? 'filtered' : ''}`} onClick={() => setFilterOpen(true)}><Filter size={16} /> Categories <span>{activeFilterCount || selectedBoards.size}</span></button><p className="result-count">Showing {visiblePlayers.length} of {matchingPlayers.length} matching runners</p></div><LeaderboardTable players={visiblePlayers} loading={!data} query={query} country={country} sortKey={sortKey} descending={descending} changeSort={changeSort} openProfile={openProfile} myRunner={myRunner} /><AutoLoadMore hasMore={visiblePlayers.length < matchingPlayers.length} label="Loading more runners" onLoadMore={() => setPlayerLimit((current) => Math.min(current + PLAYER_BATCH_SIZE, matchingPlayers.length))} /></section>
      </>}
      {view === 'history' && <section className="view-section"><div className="page-heading"><div><p className="eyebrow">Performance through time</p><h2>Historical leaderboards</h2></div><CalendarRange size={28} /></div><div className="view-toolbar history-toolbar"><div className="segmented"><button className={historyMode === 'monthly' ? 'active' : ''} onClick={() => { const latestMonth = latestMonthlyPeriod(data?.monthly || []); setHistoryMode('monthly'); setHistoryYear(String(monthParts(latestMonth)?.year || '')); setHistoryPeriod(latestMonth); }}>Monthly</button><button className={historyMode === 'yearly' ? 'active' : ''} onClick={() => { setHistoryMode('yearly'); setHistoryPeriod(String(data?.yearly.map((row) => row.year).sort((a, b) => Number(a) - Number(b)).at(-1) || '')); }}>Yearly</button></div>{historyMode === 'monthly' && <select aria-label="Monthly history year" value={historyYear} onChange={(event) => selectHistoryYear(event.target.value)}>{historyYears.map((year) => <option value={year} key={year}>{year}</option>)}</select>}<select aria-label={historyMode === 'monthly' ? 'Monthly history month' : 'Yearly history year'} value={historyPeriod} onChange={(event) => setHistoryPeriod(event.target.value)}>{historyPeriods.map((period) => <option key={period} value={period}>{historyMode === 'monthly' ? monthName(period) : period}</option>)}</select><p>{historyRows.length} ranked runners</p></div><HistoryTable rows={historyRows} flags={flags} openProfile={openProfile} /></section>}
      {view === 'lineage' && <WrLineage runs={data?.careerRuns?.length ? data.careerRuns : data?.runs || []} boards={data?.boards || []} gameNames={baseGameNames} selectedGame={lineageGame} selectedBoardKey={lineageBoard} onSelectionChange={(game, boardKey) => { setLineageGame(game); setLineageBoard(boardKey); }} />}
      {view === 'winners' && <section className="view-section"><div className="page-heading"><div><p className="eyebrow">The record book</p><h2>Monthly and yearly winners</h2></div><Trophy size={28} /></div><div className="winner-grid"><WinnerTable title="Yearly champions" icon={<Award size={18} />} rows={data?.yearlyWinners || []} periodKey="Year" flags={flags} openProfile={openProfile} /><WinnerTable title="Monthly champions" icon={<Medal size={18} />} rows={monthlyChampions} periodKey="Month" flags={flags} openProfile={openProfile} action={<select aria-label="Monthly champions year" value={winnerYear} onChange={(event) => setWinnerYear(event.target.value)}>{winnerYears.map((year) => <option value={year} key={year}>{year}</option>)}</select>} /></div></section>}
      {view === 'world' && <WorldView players={scoredPlayers} runs={filteredRuns as WorldRun[]} metadata={runnerMetadata} gameNames={baseGameNames} openProfile={openProfile} filters={{ query: worldQuery, game: worldGame, country: worldCountry, region: worldRegion }} onFiltersChange={(update) => { if (update.query !== undefined) setWorldQuery(update.query); if (update.game !== undefined) setWorldGame(update.game); if (update.country !== undefined) setWorldCountry(update.country); if (update.region !== undefined) setWorldRegion(update.region); }} />}
      {view === 'runs' && <section className="view-section"><div className="page-heading"><div><p className="eyebrow">The scoring ledger</p><h2>Explore every current run</h2></div><TableProperties size={28} /></div><div className="view-toolbar"><label className="search-box"><Search size={17} /><input value={runQuery} onChange={(event) => setRunQuery(event.target.value)} placeholder="Search runner, game or category" /></label><select value={runGame} onChange={(event) => setRunGame(event.target.value)}><option>All games</option>{data?.games.map((game) => <option value={game.abbr} key={game.abbr}>{game.name}</option>)}</select><p>Showing {visibleRuns.length} of {matchingRuns.length} matching runs</p></div><div className="data-surface"><div className="table-scroll free-height"><table className="runs-table"><thead><tr><th>Runner</th><th className="mobile-hide">Game</th><th>Board</th><th className="numeric">Place</th><th className="numeric">Time</th><th className="numeric mobile-hide">Performance</th><th className="mobile-hide">Date</th><th /></tr></thead><tbody>{visibleRuns.map((run) => <tr key={`${run.id}-${run.playerKey}`}><td><button className="runner-link" onClick={() => openProfile(run.runner)}><Flag url={flagFor(run, flags)} /><strong>{run.runner}</strong></button></td><td className="mobile-hide">{baseGameNames[run.gameAbbr] || run.gameAbbr}</td><td className="board-cell"><strong>{run.category}</strong><small className="mobile-only">{baseGameNames[run.gameAbbr] || run.gameAbbr}</small><small>{[run.level, run.subcategory].filter(Boolean).join(' · ') || run.scope}</small></td><td className="numeric">#{run.place}</td><td className="numeric mono">{run.time}</td><td className="numeric score-cell mobile-hide">{number(run.performancePoints, 2)}</td><td className="mobile-hide">{run.runDate ? new Date(run.runDate).toLocaleDateString('en-CA') : '—'}</td><td>{speedrunUrl(run.runLink) && <a className="row-action" href={speedrunUrl(run.runLink) || undefined} target="_blank" rel="noopener noreferrer"><ExternalLink size={15} /></a>}</td></tr>)}</tbody></table><AutoLoadMore hasMore={visibleRuns.length < matchingRuns.length} label="Loading more runs" onLoadMore={() => setRunLimit((current) => Math.min(current + RUN_BATCH_SIZE, matchingRuns.length))} /></div></div></section>}
      {view === 'lab' && <InsightsLab players={officialScoredPlayers} runs={filteredRuns} careerRuns={filteredCareerRuns} boards={insightBoards} gameNames={baseGameNames} openProfile={openProfile} selectedMode={labMode} selectedRunner={labRunner} onSelectionChange={(mode, runner) => { setLabMode(mode); setLabRunner(runner); }} />}
    </section>
    {filterOpen && <div className="overlay" onMouseDown={(event) => event.target === event.currentTarget && setFilterOpen(false)}><aside className="drawer filter-drawer" role="dialog" aria-modal="true"><div className="drawer-header"><div><p className="eyebrow">{extremeMode ? 'Extreme archive controls' : 'Live scoring controls'}</p><h3>Games and categories</h3></div><button className="icon-button" onClick={() => setFilterOpen(false)}><X size={18} /></button></div><div className="drawer-actions"><button onClick={resetFilters}><RotateCcw size={15} /> Reset all</button><span>{selectedBoards.size} of {data?.boards.length || 0} boards included</span></div><label className="search-box drawer-search"><Search size={16} /><input value={boardQuery} onChange={(event) => setBoardQuery(event.target.value)} placeholder="Find a category or subcategory" /></label><div className="filter-list">{boardGroups.map(({ game, boards }) => <section key={game.abbr} className="filter-group"><div className="filter-group-title"><label><input type="checkbox" checked={selectedGames.has(game.abbr)} onChange={() => toggleGame(game.abbr)} /><span>{game.name}</span></label><small>{boards.length} boards</small></div>{boards.map((board) => <label className="board-toggle" key={board.boardKey}><input type="checkbox" checked={selectedBoards.has(board.boardKey)} onChange={() => toggleBoard(board.boardKey)} /><span><strong>{board.category}</strong><small>{[board.level, board.subcategory].filter(Boolean).join(' · ') || board.scope}</small></span><em>{number(extremeMode ? extremeBoardCounts.get(board.boardKey) || 0 : board.runCount)} runs</em></label>)}</section>)}</div><div className="drawer-footer"><p>Changes are already reflected in {extremeMode ? 'Extreme Mode' : 'the leaderboard'}.</p><button className="primary-button" onClick={() => setFilterOpen(false)}>View recalculated ranks</button></div></aside></div>}
    {selectedPlayer && <div className="overlay" onMouseDown={(event) => event.target === event.currentTarget && setProfileRunner(null)}><aside className="drawer profile-drawer" role="dialog" aria-modal="true"><div className="drawer-header profile-header"><div className="profile-identity"><Flag url={selectedPlayer['Flag URL']} /><div><p className="eyebrow">{profileMode === 'extreme' ? 'Extreme rank' : 'Rank'} #{selectedPlayer.Rank}</p><h3>{selectedPlayer.Runner}</h3><span>{selectedPlayer.Country || 'Unlisted country'}</span></div></div><button className="icon-button" onClick={() => setProfileRunner(null)}><X size={18} /></button></div><div className="profile-tabs"><button className={profileTab === 'overview' ? 'active' : ''} onClick={() => setProfileTab('overview')}><UserRound size={15} /> Profile</button><button className={profileTab === 'audit' ? 'active' : ''} onClick={() => setProfileTab('audit')}><ListFilter size={15} /> Score audit</button></div>{profileTab === 'overview' ? <><ProfileOverview player={selectedPlayer} runs={selectedPlayerRuns} data={data} mode={profileMode} />{profileMode === 'current' && <div className="drawer-body runner-intelligence-body"><RunnerInsights player={officialScoredPlayers.find((player) => player.Runner === selectedPlayer.Runner) || selectedPlayer} players={officialScoredPlayers} runs={filteredRuns} boards={insightBoards} gameNames={baseGameNames} openProfile={openProfile} /></div>}</> : <ScoreAudit player={selectedPlayer} runs={selectedPlayerRuns} mode={profileMode} />}</aside></div>}
    {compareOpen && <div className="overlay centered" onMouseDown={(event) => event.target === event.currentTarget && setCompareOpen(false)}><section className="modal compare-modal" role="dialog" aria-modal="true"><div className="drawer-header"><div><p className="eyebrow">Same boards, side by side</p><h3>Head-to-head</h3></div><button className="icon-button" onClick={() => setCompareOpen(false)}><X size={18} /></button></div><div className="versus-controls"><SearchableRunnerSelect label="Runner A" search={runnerASearch} setSearch={setRunnerASearch} value={runnerA} setValue={setRunnerA} players={scoredPlayers} /><Swords size={24} /><SearchableRunnerSelect label="Runner B" search={runnerBSearch} setSearch={setRunnerBSearch} value={runnerB} setValue={setRunnerB} players={scoredPlayers} /></div><div className="comparison-summary"><ScorePill label={`${runnerA} leads`} value={String(comparison.filter((row) => row.leader === runnerA).length)} tone="red" /><ScorePill label="Shared boards" value={String(comparison.length)} tone="blue" /><ScorePill label={`${runnerB} leads`} value={String(comparison.filter((row) => row.leader === runnerB).length)} tone="green" /></div><div className="table-scroll compare-table"><table className="comparison-table"><thead><tr><th className="mobile-hide">Game</th><th>Category</th><th className="numeric mobile-hide">A place</th><th className="numeric">A time</th><th className="numeric mobile-hide">B place</th><th className="numeric">B time</th><th>Leader</th></tr></thead><tbody>{comparison.length ? comparison.map(({ runA, runB, leader }) => <tr key={runA.boardKey}><td className="mobile-hide">{baseGameNames[runA.gameAbbr] || runA.gameAbbr}</td><td className="board-cell"><strong>{runA.category}</strong><small className="mobile-only">{baseGameNames[runA.gameAbbr] || runA.gameAbbr}</small><small>{[runA.level, runA.subcategory].filter(Boolean).join(' · ')}</small></td><td className="numeric mobile-hide">#{runA.place}</td><td className="numeric mono">{runA.time}</td><td className="numeric mobile-hide">#{runB.place}</td><td className="numeric mono">{runB.time}</td><td><span className={`leader-tag ${leader === runnerA ? 'a' : leader === runnerB ? 'b' : ''}`}>{leader}</span></td></tr>) : <tr><td colSpan={7} className="empty-state">No shared included boards for these runners.</td></tr>}</tbody></table></div></section></div>}
    {updateOpen && <UpdateFeed activity={activityData} gameNames={baseGameNames} myRunner={myRunner} close={() => setUpdateOpen(false)} openProfile={openProfile} />}
    {settingsOpen && <div className="overlay" onMouseDown={(event) => event.target === event.currentTarget && setSettingsOpen(false)}><aside className="drawer settings-drawer" role="dialog" aria-modal="true"><div className="drawer-header"><div><p className="eyebrow">Personalize this view</p><h3>Settings</h3></div><button className="icon-button" aria-label="Close settings" onClick={() => setSettingsOpen(false)}><X size={18} /></button></div><nav className="settings-tabs" aria-label="Settings sections"><button className={settingsSection === 'runner' ? 'active' : ''} onClick={() => setSettingsSection('runner')}><UserRound size={16} />My Runner</button><button className={settingsSection === 'scoring' ? 'active' : ''} onClick={() => setSettingsSection('scoring')}><SlidersHorizontal size={16} />Scoring</button><button className={settingsSection === 'display' ? 'active' : ''} onClick={() => setSettingsSection('display')}><Monitor size={16} />Display</button><button className={settingsSection === 'about' ? 'active' : ''} onClick={() => setSettingsSection('about')}><Info size={16} />About</button></nav>
      {settingsSection === 'runner' && <div className="settings-body runner-settings"><div className="runner-settings-intro"><span>PERSONAL DEFAULT</span><strong>Choose your runner</strong><p>Your rank, closest rivals and latest gains will follow you throughout the site on this device.</p></div><SearchableRunnerSelect label="My Runner" search={myRunnerSearch} setSearch={setMyRunnerSearch} value={myRunner} setValue={setMyRunner} players={data?.combined || []} />{myBasePlayer ? <div className="runner-settings-card"><div><Flag url={myBasePlayer['Flag URL']} /><span><strong>{myBasePlayer.Runner}</strong><small>{myBasePlayer.Country || 'Unlisted country'}</small></span><b>#{myBasePlayer.Rank}</b></div><section><span><strong>{number(myBasePlayer['Total Score'], 2)}</strong><small>Total score</small></span><span><strong>{number(myBasePlayer['Prolific Score'])}</strong><small>Current runs</small></span><span><strong>{number(myBasePlayer.WRs)}</strong><small>WRs</small></span></section><button onClick={() => { setSettingsOpen(false); openProfile(myRunner); }}><UserRound size={15} />Open my profile</button><button onClick={() => { setSettingsOpen(false); setLabRunner(myRunner); setView('lab'); }}><Sparkles size={15} />Open my Lab</button><button onClick={() => { setSettingsOpen(false); openComparison(); }}><Swords size={15} />Start head-to-head</button></div> : <div className="runner-settings-empty"><UserRound size={23} /><p>Search the complete current leaderboard and select your runner.</p></div>}{myRunner && <button className="settings-reset runner-clear" onClick={() => setMyRunner('')}><X size={15} />Clear My Runner</button>}</div>}
      {settingsSection === 'scoring' && <div className="settings-body scoring-settings"><div className={`score-model-status ${customScoring ? 'custom' : ''}`}><span>{customScoring ? 'Custom model' : 'Official model'}</span><strong>Performance × {performanceWeight} + {volumeCoefficient} × √runs + {varietyPerGame} × extra games</strong><small>Custom scoring changes current Ranks, Extreme Mode, profiles and World. Historical tables and Insights Lab stay on the official model.</small></div><div className="score-presets"><span>Presets</span><div><button onClick={() => { setPerformanceWeight(1); setVolumeCoefficient(8); setVarietyPerGame(10); }}>Official</button><button onClick={() => { setPerformanceWeight(1.25); setVolumeCoefficient(5); setVarietyPerGame(6); }}>Performance</button><button onClick={() => { setPerformanceWeight(.8); setVolumeCoefficient(14); setVarietyPerGame(12); }}>Prolific</button><button onClick={() => { setPerformanceWeight(1); setVolumeCoefficient(9); setVarietyPerGame(15); }}>All-rounder</button></div></div><label className="score-control"><span><strong>Performance weight</strong><output>{performanceWeight.toFixed(2)}×</output></span><input type="range" min="0" max="2" step="0.05" value={performanceWeight} onChange={(event) => setPerformanceWeight(Number(event.target.value))} /><small>Scales every run&apos;s placement and leaderboard-depth contribution.</small></label><label className="score-control"><span><strong>Volume coefficient</strong><output>{volumeCoefficient.toFixed(1)}</output></span><input type="range" min="0" max="20" step="0.5" value={volumeCoefficient} onChange={(event) => setVolumeCoefficient(Number(event.target.value))} /><small>Controls the diminishing-return bonus applied to the square root of run count.</small></label><label className="score-control"><span><strong>Variety per additional game</strong><output>{varietyPerGame.toFixed(0)}</output></span><input type="range" min="0" max="25" step="1" value={varietyPerGame} onChange={(event) => setVarietyPerGame(Number(event.target.value))} /><small>Rewards engine breadth after a runner&apos;s first represented game.</small></label><button className="settings-reset" disabled={!customScoring} onClick={() => { setPerformanceWeight(1); setVolumeCoefficient(8); setVarietyPerGame(10); }}><RotateCcw size={15} />Restore official scoring</button></div>}
      {settingsSection === 'display' && <div className="settings-body display-settings"><section><span>Leaderboard density</span><div className="segmented"><button className={density === 'comfortable' ? 'active' : ''} onClick={() => setDensity('comfortable')}>Comfortable</button><button className={density === 'compact' ? 'active' : ''} onClick={() => setDensity('compact')}>Compact</button></div></section><label className="settings-toggle"><input type="checkbox" checked={showFlags} onChange={(event) => setShowFlags(event.target.checked)} /><span><strong>Show flags</strong><small>Display public location flags beside runner names.</small></span></label><label className="settings-toggle"><input type="checkbox" checked={reduceMotion} onChange={(event) => setReduceMotion(event.target.checked)} /><span><strong>Reduce motion</strong><small>Disable animated playback and interface movement.</small></span></label><p>Display preferences are stored in the shareable URL alongside the active view.</p></div>}
      {settingsSection === 'about' && <div className="settings-body settings-about"><strong>A searchable home for the SMB1 engine community.</strong><p>This website is an interpretation of Loopie&apos;s SMB1 Engine Combined Leaderboard Google Sheet, designed to make its standings easier to search, filter, compare and explore.</p><section><h4>Inspiration</h4><p>Inspired by aaron2u2&apos;s Most Prolific NES Runners list and CyanBeast&apos;s website using Loopie&apos;s combined leaderboard.</p></section><section><h4>Purpose</h4><p>This is not a replacement for Speedrun.com or the projects that inspired it. It is an interactive community reference built from public leaderboard data.</p></section><section><h4>Data and scoring</h4><p>Current Ranks use non-obsolete runs. Extreme Mode counts every accepted archive submission. Monthly history uses verification dates; yearly history prefers performed dates.</p></section><p className="sprite-credit">Sprite accents from <a href="https://www.mariouniverse.com/sprites-nes-smb/" target="_blank" rel="noreferrer">Mario Universe</a>. Geographic data from Natural Earth.</p></div>}
    </aside></div>}
  </main>;
}

function LeaderboardTable({ players, loading, query, country, sortKey, descending, changeSort, openProfile, myRunner }: { players: Player[]; loading: boolean; query: string; country: string; sortKey: SortKey; descending: boolean; changeSort: (key: SortKey) => void; openProfile: (runner: string, tab?: ProfileTab) => void; myRunner: string }) { return <div className="table-scroll"><table className="leaderboard-table"><thead><tr><th className="rank-column"><button onClick={() => changeSort('Rank')}>Rank{sortKey === 'Rank' && (descending ? <ArrowDown size={13} /> : <ArrowUp size={13} />)}</button></th><th>Runner</th>{columns.map((column) => <th key={column.key} className={`numeric ${column.key === 'Total Score' ? '' : 'mobile-hide'}`}><button onClick={() => changeSort(column.key)}>{column.label}{sortKey === column.key && (descending ? <ArrowDown size={13} /> : <ArrowUp size={13} />)}</button></th>)}<th className="numeric mobile-hide">Games</th><th className="mobile-hide" /></tr></thead><tbody>{loading && Array.from({ length: 10 }, (_, index) => <tr className="loading-row" key={index}><td colSpan={9}><span /></td></tr>)}{players.map((player) => <tr key={player.playerKey || player.Runner} className={`${player.Rank <= 3 && !query && country === 'All countries' ? `podium podium-${player.Rank}` : ''} ${player.Runner === myRunner ? 'my-runner-row' : ''}`.trim()}><td className="rank-cell"><span>{player.Rank}</span></td><td><button className="runner-cell" onClick={() => openProfile(player.Runner)}><Flag url={player['Flag URL']} /><span><strong>{player.Runner}{player.Runner === myRunner && <em className="my-runner-tag">ME</em>}</strong><small>{player.Country || 'Unlisted country'}</small><small className="mobile-player-stats">{number(player['Prolific Score'])} runs · {number(player['Unique Boards'])} boards · {number(player.WRs)} WRs</small></span></button></td><td className="numeric score-cell">{number(player['Total Score'], 2)}</td><td className="numeric mobile-hide">{number(player['Performance Score'], 2)}</td><td className="numeric mobile-hide">{number(player['Prolific Score'])}</td><td className="numeric mobile-hide">{number(player['Unique Boards'])}</td><td className="numeric mobile-hide">{number(player.WRs)}</td><td className="numeric mobile-hide">{number(player['Unique Games'])}</td><td className="mobile-hide"><button className="row-action" onClick={() => openProfile(player.Runner)}><UserRound size={16} /><ChevronRight size={14} /></button></td></tr>)}</tbody></table></div>; }

function SearchableRunnerSelect({ label, search, setSearch, value, setValue, players }: { label: string; search: string; setSearch: (value: string) => void; value: string; setValue: (value: string) => void; players: Player[] }) {
  const [open, setOpen] = useState(false);
  const needle = search.trim().toLocaleLowerCase();
  const matches = players.filter((player) => !needle || String(player.Runner).toLocaleLowerCase().includes(needle));
  const listId = `${label.toLocaleLowerCase().replace(/\s+/g, '-')}-results`;
  return <div className="runner-picker" onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget)) { setOpen(false); setSearch(''); } }}><span>{label}</span><small>{value ? `Rank #${players.find((player) => player.Runner === value)?.Rank || '—'}` : 'Choose runner'}</small><div className="runner-combobox"><Search size={15} /><input role="combobox" aria-label={`Search ${label}`} aria-expanded={open} aria-controls={listId} value={open ? search : value} onFocus={() => { setOpen(true); setSearch(''); }} onChange={(event) => { setSearch(event.target.value); setOpen(true); }} placeholder={`Search ${label.toLocaleLowerCase()}`} /><ChevronDown size={16} />{open && <div className="runner-results" id={listId} role="listbox">{matches.slice(0, 80).map((player) => <button type="button" role="option" aria-selected={player.Runner === value} key={player.playerKey || player.Runner} onMouseDown={(event) => { event.preventDefault(); setValue(String(player.Runner)); setSearch(''); setOpen(false); }}><Flag url={player['Flag URL']} /><span><strong>{player.Runner}</strong><small>{player.Country || 'Unlisted country'}</small></span><em>#{player.Rank}</em>{player.Runner === value && <Check size={14} />}</button>)}{matches.length === 0 && <p>No runners found.</p>}</div>}</div></div>;
}

function ProfileOverview({ player, runs, data, mode = 'current' }: { player: Player; runs: Run[]; data: SiteData | null; mode?: 'current' | 'extreme' }) { const byGame = useMemo(() => Array.from(runs.reduce((map, run) => { const key = baseGame(run.gameToggle); const row = map.get(key) || { runs: 0, points: 0, wr: 0 }; row.runs += 1; row.points += run.performancePoints; row.wr += run.wrCredit; map.set(key, row); return map; }, new Map<string, { runs: number; points: number; wr: number }>()).entries()).sort((a, b) => b[1].points - a[1].points), [runs]); const yearly = mode === 'current' ? (data?.yearly || []).filter((row) => row.runner === player.Runner).sort((a, b) => Number(b.year) - Number(a.year)) : []; return <div className="drawer-body"><div className="profile-score"><span>{mode === 'extreme' ? 'Extreme total score' : 'Total score'}</span><strong>{number(player['Total Score'], 2)}</strong><small>#{player.Rank} under the {mode === 'extreme' ? 'accepted-archive' : 'current'} filters</small></div><div className="score-grid"><ScorePill label="Performance" value={number(player['Performance Score'], 2)} tone="blue" /><ScorePill label="Volume" value={number(player['Volume Bonus'], 2)} /><ScorePill label="Variety" value={number(player['Variety Bonus'], 2)} tone="green" /><ScorePill label={mode === 'extreme' ? 'Accepted runs' : 'Current runs'} value={number(player['Prolific Score'])} /></div><div className="stat-line"><span><strong>{number(player.WRs)}</strong> WRs</span><span><strong>{number(player['Top 3s'])}</strong> top 3s</span><span><strong>{number(player['Unique Boards'])}</strong> boards</span><span><strong>{number(player['Unique Games'])}</strong> games</span></div><section className="profile-section"><h4>Game breakdown</h4>{byGame.map(([game, stats]) => <div className="breakdown-row" key={game}><strong>{baseGameNames[game] || game}</strong><span>{stats.runs} runs</span><span>{number(stats.wr)} WRs</span><em>{number(stats.points, 2)} pts</em></div>)}</section><section className="profile-section"><h4>Best scoring runs</h4>{runs.slice(0, 8).map((run) => <a className="audit-row compact" href={speedrunUrl(run.runLink) || undefined} target="_blank" rel="noopener noreferrer" key={`${run.id}-${run.playerKey}`}><span><strong>{baseGameNames[run.gameAbbr] || run.gameAbbr} · {run.category}</strong><small>{[run.level, run.subcategory].filter(Boolean).join(' · ') || run.time}</small></span><em>#{run.place}</em><b>{number(run.performancePoints, 2)}</b></a>)}</section>{yearly.length > 0 && <section className="profile-section"><h4>Yearly history</h4>{yearly.slice(0, 8).map((row) => <div className="history-line" key={row.year}><strong>{row.year}</strong><span>Rank #{row.rank}</span><em>{number(row.totalScore, 2)}</em></div>)}</section>}{speedrunUrl(player.Profile) && <a className="external-button" href={speedrunUrl(player.Profile) || undefined} target="_blank" rel="noopener noreferrer">Speedrun.com profile <ExternalLink size={15} /></a>}</div>; }

function ScoreAudit({ player, runs, mode = 'current' }: { player: Player; runs: Run[]; mode?: 'current' | 'extreme' }) { return <div className="drawer-body"><div className="audit-equation"><div><span>Performance</span><strong>{number(player['Performance Score'], 2)}</strong></div><b>+</b><div><span>Volume</span><strong>{number(player['Volume Bonus'], 2)}</strong></div><b>+</b><div><span>Variety</span><strong>{number(player['Variety Bonus'], 2)}</strong></div><b>=</b><div className="total"><span>Total</span><strong>{number(player['Total Score'], 2)}</strong></div></div><p className="audit-note">{mode === 'extreme' ? 'Every accepted archive submission is listed, including obsolete improvements. Places are recalculated against all accepted submissions on that board.' : 'The rows below reconcile the performance portion. Times stay in speedrun format; no spreadsheet decimals.'}</p><section className="profile-section"><h4>Run contributions</h4>{runs.map((run) => <a className="audit-row" href={speedrunUrl(run.runLink) || undefined} target="_blank" rel="noopener noreferrer" key={`${run.id}-${run.playerKey}-${run.boardKey}`}><span><strong>{baseGameNames[run.gameAbbr] || run.gameAbbr} · {run.category}</strong><small>{[run.level, run.subcategory].filter(Boolean).join(' · ') || `${run.boardSize} runners`}</small></span><em>#{run.place}<small>{run.time}</small></em><b>{number(run.performancePoints, 2)}<small>performance</small></b></a>)}</section></div>; }

function HistoryTable({ rows, flags, openProfile }: { rows: HistoryRow[]; flags: Map<string, string | null>; openProfile: (runner: string) => void }) { return <div className="data-surface"><div className="table-scroll free-height"><table className="history-table"><thead><tr><th className="rank-column">Rank</th><th>Runner</th><th className="numeric">Total</th><th className="numeric mobile-hide">Performance</th><th className="numeric">Runs</th><th className="numeric mobile-hide">Volume</th><th className="numeric mobile-hide">Variety</th><th className="numeric mobile-hide">Boards</th><th className="numeric mobile-hide">Games</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.rank}-${row.runner}`}><td className="rank-cell"><span>{row.rank}</span></td><td><button className="runner-cell" onClick={() => openProfile(row.runner)}><Flag url={flagFor(row, flags)} /><span><strong>{row.runner}</strong><small>{row.country || 'Unlisted country'}</small></span></button></td><td className="numeric score-cell">{number(row.totalScore, 2)}</td><td className="numeric mobile-hide">{number(row.performanceScore, 2)}</td><td className="numeric">{number(row.runs)}</td><td className="numeric mobile-hide">{number(row.volumeBonus, 2)}</td><td className="numeric mobile-hide">{number(row.varietyBonus, 2)}</td><td className="numeric mobile-hide">{number(row.uniqueBoards)}</td><td className="numeric mobile-hide">{number(row.uniqueGames)}</td></tr>)}</tbody></table></div></div>; }

function WinnerTable({ title, icon, rows, periodKey, flags, openProfile, action }: { title: string; icon: React.ReactNode; rows: WinnerRow[]; periodKey: 'Year' | 'Month'; flags: Map<string, string | null>; openProfile: (runner: string) => void; action?: React.ReactNode }) { return <section className="winner-surface"><div className="winner-heading"><h3>{icon}{title}</h3>{action}</div><div className="winner-list">{rows.map((row, index) => { const runner = String(row.Winner || ''); const period = periodKey === 'Month' ? monthLabel(String(row[periodKey])) : String(row[periodKey]); return <button className="winner-row" onClick={() => openProfile(runner)} key={`${period}-${runner}`}><span className="winner-medal">{index + 1}</span><span className="winner-period">{period}</span><Flag url={flags.get(runner) || null} /><span className="winner-name"><strong>{runner}</strong><small>{String(row.Country || '')}</small></span><em>{number(Number(row['Total Score']), 2)}</em><ChevronRight size={15} /></button>; })}</div></section>; }
